[package]
name = "formslang-desktop"
version = "0.1.2"
description = "FormsLang desktop shell (B2DEV TECH)"
edition = "2021"
license = "Apache-2.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"

[profile.release]
strip = true
lto = true
