"""Guided modernization reading paths in the existing Workbench."""

BLUEPRINT_JS = r"""
let bpRequest=0,bpOffset=0,bpScreen=0,bpContext=null,bpSelectedFinding='',bpSelectedNode='';
let bpAdvisory=null,bpHistory=[],bpDraftScope='',bpSearchTimer=null;
const bpDrafts=new Map(),bpPolls=new Map(),bpAIRequests=new Map();
window.addEventListener('beforeunload',e=>{if(bpDrafts.size){e.preventDefault();e.returnValue='';}});
const bpAlive=c=>!!c && c===bpContext && c.screen===bpScreen && c.generation===modalGeneration && !!$('bp');
function bpDetach(){for(const timer of bpPolls.values())clearTimeout(timer);bpPolls.clear();clearTimeout(bpSearchTimer);++bpRequest;}
window.addEventListener('formslang:modalchange',bpDetach);
const BP_DECISIONS=['PRESERVE','CONVERT','REFACTOR','WRAP_AS_API','DROP','MANUAL_REVIEW','UNKNOWN'];
const BP_COVERAGE=['REQUIRES_REVIEW','PRESERVED','CONVERTED','REFACTORED','DROPPED_INTENTIONALLY','UNSUPPORTED','UNKNOWN'];
const BP_FILTERS={module:'bp-module',entity_type:'bp-type',dependency_type:'bp-dependency',decision:'bp-decision',review:'bp-review',domain:'bp-domain',risk_level:'bp-risk',query:'bp-search'};
const BP_LABELS={PRESERVE:'Keep existing logic',CONVERT:'Convert to APEX',REFACTOR:'Restructure the logic',WRAP_AS_API:'Consider an API',DROP:'Remove after review',MANUAL_REVIEW:'Investigate first',UNKNOWN:'Not established',TRIGGER:'Trigger',PROGRAM_UNIT:'Program unit',FORM:'Form',BLOCK:'Block',ITEM:'Field',BUSINESS_RULE:'Rule candidate',PACKAGE_REFERENCE:'Package reference',ROUTINE_REFERENCE:'Routine reference',TABLE_OR_VIEW_REFERENCE:'Table / view reference',BUILTIN:'Forms built-in',INTEGRATION_POINT:'Integration',UI_BEHAVIOR:'Screen behavior',DATA_ACCESS:'Data access',NAVIGATION:'Navigation',TRANSACTION_CONTROL:'Transaction control',INTEGRATION:'Integration',PENDING:'Not reviewed',APPROVE:'Accept recommendation',MODIFY:'Choose another approach',REJECT:'Reject recommendation',DEFER:'Decide later',STALE:'Source changed — review again',REQUIRES_REVIEW:'Not implemented / needs review',PRESERVED:'Preserved',CONVERTED:'Converted',REFACTORED:'Refactored',DROPPED_INTENTIONALLY:'Intentionally removed',UNSUPPORTED:'Unsupported',FACT:'Observed in source',INFERENCE:'Analysis suggestion',ASSUMPTION:'Assumption to confirm',CALLS:'calls',READS:'reads',WRITES:'writes',REFERENCES:'references',CONTAINS:'contains',USES_PROGRAM_UNIT:'uses local logic',OPENS_FORM:'opens form',NAVIGATES_TO:'navigates to',COMMITS:'commits through',EXECUTES_QUERY:'executes query through',INVOKES_BUILTIN:'invokes',USES_LOV:'uses list of values'};
const bpLabel=v=>BP_LABELS[v]||String(v||'Unknown').toLowerCase().replaceAll('_',' ');
const bpOptions=(values,first)=>(first?`<option value="">${esc(first)}</option>`:'')+values.map(v=>`<option value="${esc(v)}">${esc(bpLabel(v))}</option>`).join('');
const bpChip=v=>`<span class="bp-chip">${esc(bpLabel(v))}</span>`;
const bpNode=n=>`<button class="bp-link" data-bp-node="${esc(n.id)}">${esc(n.name)}</button>`;
const BP_STYLE=`
.sheet:has(#bp){width:min(1440px,97vw);height:94vh;max-height:94vh}.sheet:has(#bp) #modal-body{padding:0}
#bp{--bp-accent:var(--gold);--bp-blue:var(--blue);--bp-green:var(--green);padding:22px 26px 30px;color:var(--ink);font-size:14px}#bp *{box-sizing:border-box}#bp [hidden]{display:none!important}
#bp h2,#bp h3,#bp h4,#bp p{margin:0}#bp h2{font-size:clamp(22px,2.4vw,32px);line-height:1.2;letter-spacing:-.6px}#bp h3{font-size:18px}#bp h4{font-size:14px}#bp p{line-height:1.65}#bp small,.bp-muted{color:var(--ink-dim);line-height:1.5}
#bp button:focus-visible,#bp a:focus-visible,#bp summary:focus-visible{outline:2px solid var(--bp-blue);outline-offset:3px}#bp button{cursor:pointer}#bp button:disabled{cursor:default;opacity:.55}
.bp-eyebrow{font-size:11px;letter-spacing:1.8px;text-transform:uppercase;color:var(--bp-accent);font-weight:700}.bp-hero{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:22px}.bp-hero h2{margin:8px 0!important;overflow-wrap:anywhere}.bp-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.bp-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;border-bottom:1px solid var(--line);margin-bottom:22px;padding-bottom:12px;flex-wrap:wrap}
.bp-nav{display:flex;gap:6px;flex-wrap:wrap}.bp-nav button{border:0;color:var(--ink-dim);background:transparent;border-radius:8px;padding:11px 14px;font-weight:600}.bp-nav button[aria-pressed=true]{background:#ffb84d19;color:var(--bp-accent)}.bp-nav b{margin-right:7px;opacity:.7}
.bp-card{border:1px solid var(--line);border-radius:13px;padding:20px;background:var(--panel)}.bp-card h3{margin-bottom:8px!important}.bp-stack{display:grid;gap:16px}.bp-columns{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(300px,1fr);gap:20px;align-items:start}.bp-two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.bp-ai-card{background:linear-gradient(145deg,#89bbff14,transparent 65%);border-color:#89bbff45}.bp-ai-card .bp-eyebrow{color:var(--bp-blue)}.bp-ai-card h3{margin-top:9px!important;font-size:21px!important}.bp-ai-card .btn{margin-top:14px}.bp-ai-card small{display:block;margin-top:12px}
.bp-categories{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:18px}.bp-category{border:1px solid var(--line);background:transparent;color:var(--ink);border-radius:10px;padding:14px;text-align:left;display:grid;gap:6px}.bp-category:hover,.bp-row:hover{background:#89bbff0b;border-color:#89bbff70}.bp-category b{font-size:27px;line-height:1}.bp-category span{font-weight:600}.bp-category small{font-size:11px}
.bp-route{display:grid;grid-template-columns:minmax(0,1fr) 105px minmax(0,1fr);gap:10px;align-items:center;padding:12px 0;border-top:1px solid var(--line)}.bp-route:first-child{border-top:0}.bp-route-node{min-width:0;border:1px solid #89bbff35;border-radius:9px;padding:12px;background:#89bbff08;overflow-wrap:anywhere}.bp-route-node small{display:block;font-size:11px;margin-bottom:4px}.bp-route-target{border-color:#72d5bc40;background:#72d5bc08}.bp-route-edge{text-align:center;color:var(--ink-dim);font-size:11px}.bp-route-edge svg{width:100%;height:18px;display:block;color:var(--bp-blue)}.bp-link{border:0;background:none;color:var(--bp-blue);padding:0;text-align:left;text-decoration:underline;text-underline-offset:3px;font:inherit;overflow-wrap:anywhere}
.bp-section-title{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px}.bp-chip{font-size:11px;display:inline-block;color:var(--ink-dim);border:1px solid var(--line);border-radius:5px;padding:3px 7px;margin:3px 4px 3px 0}.bp-row{width:100%;display:flex;align-items:center;text-align:left;gap:12px;padding:14px;border:1px solid var(--line);border-radius:10px;background:transparent;color:var(--ink)}.bp-row-text{min-width:0;flex:1;overflow-wrap:anywhere}.bp-row-text strong{display:block}.bp-row-text small{display:block;margin-top:4px}.bp-index{background:#ffb84d13;color:var(--bp-accent);border-radius:8px;padding:7px 10px;font-weight:700}.bp-arrow{color:var(--bp-accent);font-size:22px}
#bp details{margin-top:14px}#bp summary{cursor:pointer;color:var(--ink-dim);padding:4px 0}#bp details[open]>summary{margin-bottom:12px}#bp label{display:grid;gap:6px;font-size:12px;color:var(--ink-dim)}#bp input,#bp select,#bp textarea{width:100%;min-width:0;padding:10px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:var(--ink);font:inherit}#bp input[type=checkbox]{width:auto}#bp textarea{min-height:80px;resize:vertical}#bp pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:360px;overflow:auto;font-size:12px;line-height:1.6}
.bp-filters{display:grid;grid-template-columns:2fr 1fr 1fr;gap:12px}.bp-extra-filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.bp-explorer{display:grid;grid-template-columns:minmax(240px,1fr) minmax(0,2fr);gap:18px;margin-top:16px}.bp-list{display:grid;align-content:start;gap:7px;max-height:70vh;overflow:auto}.bp-list .bp-row{display:block}.bp-list .bp-row[aria-pressed=true]{border-color:var(--bp-accent);background:#ffb84d0d}.bp-list strong{font-size:13px;overflow-wrap:anywhere}.bp-list small{display:block;margin-top:5px}.bp-detail{min-width:0}.bp-detail>p{margin-top:9px!important}.bp-evidence{border-left:2px solid var(--bp-blue);background:#89bbff07;padding:12px;margin:8px 0}.bp-detail h3{overflow-wrap:anywhere}.bp-recommendation{background:#ffb84d0b;border:1px solid #ffb84d35;border-radius:10px;padding:16px;margin:16px 0}.bp-recommendation h4{color:var(--bp-accent);font-size:17px!important;margin:8px 0!important}.bp-deps{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.bp-deps .bp-chip{padding:8px}.bp-review-form{border-top:1px solid var(--line);padding-top:16px;margin-top:16px}.bp-review-form label{margin-bottom:12px}.bp-note{border-left:3px solid var(--bp-accent);padding:10px 14px;margin-bottom:16px;background:#ffb84d0b}.bp-page{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:14px}.bp-target{display:grid;grid-template-columns:1fr 1fr;gap:20px}.bp-target section{border-left:3px solid var(--bp-green)}.bp-target h4{font-size:18px!important;margin-bottom:8px!important}.bp-strategy{display:grid;gap:10px;margin-top:18px}.bp-strategy .bp-row b{font-size:23px;min-width:35px}.bp-ai-section{border-top:1px solid var(--line);padding-top:14px;margin-top:14px}.bp-ai-section h4{margin-bottom:8px!important}.bp-ai-section p{white-space:pre-wrap}.bp-progress{height:6px;background:var(--line);border-radius:4px;overflow:hidden;margin:12px 0}.bp-progress span{display:block;background:var(--bp-green);height:100%}.bp-empty{padding:25px;text-align:center}.bp-empty h3{margin-bottom:12px!important}
@media(max-width:1000px){.bp-columns{grid-template-columns:1fr}.bp-hero{align-items:start}.bp-explorer{grid-template-columns:280px minmax(0,1fr)}}
@media(max-width:720px){#bp{padding:16px}.bp-hero{display:block}.bp-hero>.bp-actions{margin-top:14px}.bp-explorer,.bp-two,.bp-target{grid-template-columns:1fr}.bp-list{max-height:260px}.bp-filters,.bp-extra-filters{grid-template-columns:1fr 1fr}.bp-filters label:first-child{grid-column:1/-1}.bp-categories{grid-template-columns:1fr 1fr}.bp-route{grid-template-columns:minmax(0,1fr) 65px minmax(0,1fr);gap:6px}.bp-route-node{padding:8px}.bp-route-node .bp-link{font-size:12px}.bp-nav button{padding:9px;font-size:12px}.bp-page{flex-wrap:wrap}}`;
const BP_COMPACT_STYLE=`
#bp .bp-hero h2{font-size:22px}#bp .bp-card h3{font-size:17px}
#bp{padding:14px 20px 24px}.bp-hero{padding:0;margin-bottom:12px;min-height:0;border:0;background:none}.bp-hero h2{font-size:22px;margin:0 0 5px!important}.bp-hero p{font-size:12px}.bp-toolbar{position:sticky;top:0;z-index:3;background:var(--panel);padding:8px 0;margin-bottom:16px}.bp-card{padding:16px}.bp-columns{grid-template-columns:minmax(0,1.65fr) minmax(300px,1fr);gap:16px}.bp-categories{margin-top:12px}.bp-category{padding:11px;gap:4px}.bp-category b{font-size:24px}.bp-card h3{font-size:17px}.bp-route{padding:9px 0}.bp-route-node{padding:10px}.bp-ai-status:not(:empty){margin-top:12px!important;padding:10px;border-radius:7px;background:#89bbff0a;border:1px solid #89bbff25;font-size:12px}.bp-ai-status[data-running=true]:before{content:'';display:inline-block;width:9px;height:9px;background:var(--bp-blue);border-radius:50%;margin-right:8px;animation:bpPulse 1.5s ease-in-out infinite}.bp-ai-section{margin-top:10px;padding-top:5px}.bp-ai-section summary{font-weight:600;color:var(--ink)!important;line-height:1.4}.bp-ai-section p{font-size:13px}.bp-draft{color:var(--bp-accent);font-size:12px}.bp-detail-head{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:12px}.bp-code-tools{display:flex;justify-content:space-between;align-items:center;gap:10px}.bp-code-tools button{font-size:11px}#bp-detail{scroll-margin-top:75px}#bp-status:not(:empty){margin:10px 0;overflow-wrap:anywhere}#bp-export-status{overflow-wrap:anywhere}
@keyframes bpPulse{50%{opacity:.35}}@media(prefers-reduced-motion:reduce){.bp-ai-status:before{animation:none!important}}
@media(max-width:1000px){.bp-columns{grid-template-columns:1fr}.bp-hero{align-items:start}}
@media(max-width:720px){#bp{padding:12px}.bp-hero{display:block}.bp-toolbar>small{display:none}.bp-hero>.bp-actions{margin-top:10px}.bp-nav{gap:0}.bp-nav button{padding:9px 7px}.bp-card{padding:13px}.bp-ai-card h3{font-size:18px!important}.bp-detail-head{flex-wrap:wrap}}
`;
async function showBlueprint(selectedNode=''){
 const previous=selectedNode?Object.fromEntries(Object.values(BP_FILTERS).map(id=>[id,$(id)?.value||''])):{};
 const screen=++bpScreen;bpDetach();openModal('Modernization Blueprint');foot(null);
 $('modal-path').textContent='';$('modal-hint').textContent='Understand the application. Inspect the evidence. Decide what to modernize.';
 $('modal-body').innerHTML='<p style="padding:24px" role="status">Opening application analysis…</p>';
 const generation=modalGeneration;
 let d;try{d=await api('/api/blueprint');}catch(e){if(screen===bpScreen&&generation===modalGeneration)$('modal-body').textContent=e.message;return;}
 if(screen!==bpScreen||generation!==modalGeneration)return;
 bpContext={d,screen,generation};bpAdvisory=null;bpSelectedFinding='';
 const scope=d.context_id||JSON.stringify(d.application);if(scope!==bpDraftScope){bpHistory=[];bpSelectedNode='';bpDraftScope=scope;}
 $('modal-body').innerHTML=`<style>${BP_STYLE}${BP_COMPACT_STYLE}</style><div id="bp"><div class="bp-hero"><div><h2>${esc(d.available?d.application.name:'Start with the application you have')}</h2><p class="bp-muted">${d.available?`${d.summary.entities.FORM||0} form(s) · ${d.guide.code_total} code units · local source analysis`:'Turn the open Forms module into a connected reading guide.'}</p></div><div class="bp-actions">${d.available?'<a class="btn" href="/api/blueprint/report" target="_blank" rel="noopener">Open report ↗</a>':''}<button class="btn" id="bp-settings-toggle">Analysis settings</button></div></div>
 <div id="bp-settings" class="bp-card" hidden><h3>Source and analysis options</h3><div class="bp-filters"><label>Application folder (optional)<input id="bp-source" placeholder="Leave empty to use the open module"></label><label>Enterprise naming patterns<input type="checkbox" id="bp-enterprise" ${d.available&&d.enterprise_context.enabled?'checked':''}></label><button class="btn" id="bp-build">${d.available?'Refresh source analysis':'Analyze open module'}</button></div><p class="bp-muted">A folder analyzes multiple modules. Refreshing changed source can make previous architecture decisions stale.</p></div><div id="bp-status" role="status"></div>
 ${d.available?bpOverview(d):'<section class="bp-card bp-empty"><div class="bp-eyebrow">Your first Blueprint</div><h3>See how the open form is connected</h3><p>Find its rules, data references and integration points. Then use AI to help explain the structure and plan your review.</p><p style="margin-top:20px"><button class="btn primary" id="bp-start">Analyze open module →</button></p><small>Source analysis runs locally. AI is a separate action using your configured provider.</small></section>'}</div>`;
 $('bp-settings-toggle').onclick=()=>{$('bp-settings').hidden=!$('bp-settings').hidden;};
 $('bp-build').onclick=async()=>{
  const context=bpContext,button=$('bp-build'),status=$('bp-status');
  const body={path:$('bp-source').value,enterprise:$('bp-enterprise').checked,context_id:context.d.context_id};
  button.disabled=true;if($('bp-start'))$('bp-start').disabled=true;status.textContent='Reading source, rules and dependencies…';
  try{await api('/api/blueprint/build',body);if(bpAlive(context)){await refresh();if(bpAlive(context))await showBlueprint();}}
  catch(e){if(bpAlive(context)){status.textContent=e.message;button.disabled=false;if($('bp-start'))$('bp-start').disabled=false;}}
 };
 if(!d.available){$('bp-start').onclick=()=>$('bp-build').click();return;}
 for(const link of $('bp').querySelectorAll('a[href^="/api/blueprint/"]')){const url=new URL(link.href);url.searchParams.set('context_id',d.context_id||'');link.href=url.pathname+url.search;}
 for(const [id,value] of Object.entries(previous))$(id).value=value;
 $('bp').addEventListener('click',e=>{const node=e.target.closest('[data-bp-node]'),tab=e.target.closest('[data-bp-tab]'),filter=e.target.closest('[data-bp-filter]');if(node){bpTab('inspect',false);bpExplore(node.dataset.bpNode);}else if(tab)bpTab(tab.dataset.bpTab);else if(filter)bpFilter(JSON.parse(filter.dataset.bpFilter));});
 $('bp-export').onclick=async()=>{const context=bpContext,button=$('bp-export');button.disabled=true;try{const r=await api('/api/blueprint/export',{context_id:context.d.context_id});if(bpAlive(context))$('bp-export-status').textContent='Reports saved to '+r.path;}catch(e){if(bpAlive(context))$('bp-export-status').textContent=e.message;}finally{if(bpAlive(context))button.disabled=false;}};
 $('bp-ai-overview').onclick=()=>bpStartAI('application');$('bp-ai-save').onclick=()=>bpSaveBriefing(d);$('bp-ai-cancel').onclick=()=>bpCancelAI('application');$('bp-ai-settings').onclick=()=>openSettings();$('bp-clear').onclick=()=>bpFilter({});
 for(const id of Object.values(BP_FILTERS).filter(id=>id!=='bp-search'))$(id).onchange=()=>bpExplore('',0);
 $('bp-search').oninput=()=>{clearTimeout(bpSearchTimer);const context=bpContext;bpSearchTimer=setTimeout(()=>{if(bpAlive(context))bpExplore('',0);},250);};
 bpResumeAI('application');bpTab(selectedNode?'inspect':'understand',!selectedNode);if(selectedNode)await bpExplore(selectedNode,0);
}
function bpFilterButton(filters,body,cls='bp-category'){return `<button class="${cls}" data-bp-filter="${esc(JSON.stringify(filters))}">${body}</button>`;}
function bpRoutes(paths){return paths.map(p=>`<div class="bp-route"><div class="bp-route-node"><small>${esc(bpLabel(p.source.type))}${p.source.owner?' · '+esc(p.source.owner):''}</small>${bpNode(p.source)}</div><div class="bp-route-edge">${esc(bpLabel(p.relationship))}<svg viewBox="0 0 100 18" aria-hidden="true"><path d="M2 9H94M86 3L94 9L86 15" fill="none" stroke="currentColor" stroke-width="1.5"/></svg><span>${esc(bpLabel(p.level))}</span></div><div class="bp-route-node bp-route-target"><small>${esc(bpLabel(p.target.type))}</small>${bpNode(p.target)}</div></div>`).join('');}
function bpOverview(d){
 const g=d.guide,c=t=>d.summary.entities[t]||0;
 const categories=[['Rules to understand',c('BUSINESS_RULE'),{entity_type:'BUSINESS_RULE'},'Conditional rejection candidates'],['Data references',c('TABLE_OR_VIEW_REFERENCE'),{entity_type:'TABLE_OR_VIEW_REFERENCE'},'Tables / views mentioned in source'],['Triggers to inspect',c('TRIGGER'),{entity_type:'TRIGGER'},'Behavior attached to the screen']];
 const accepted=g.code_total?Math.round(g.code_reviewed/g.code_total*100):0;
 return `<nav class="bp-toolbar" aria-label="Blueprint steps"><div class="bp-nav"><button data-bp-tab="understand" aria-pressed="true"><b>01</b> Understand</button><button data-bp-tab="inspect" aria-pressed="false"><b>02</b> Inspect & decide</button><button data-bp-tab="plan" aria-pressed="false"><b>03</b> Modernization plan</button></div><small>Source facts + human decisions</small></nav>
 ${d.stale_engine?'<div class="bp-note">The analysis engine changed. Refresh the source analysis before making decisions.</div>':''}
 ${d.failures.length?`<div class="bp-note">${d.failures.length} source(s) could not be analyzed. This view is incomplete.<details><summary>See sources</summary><pre>${esc(JSON.stringify(d.failures,null,2))}</pre></details></div>`:''}
 <div id="bp-understand" class="bp-stack"><div class="bp-columns"><div class="bp-stack">
 <section class="bp-card"><h3>What is inside this application?</h3><p>${c('BLOCK')} blocks organize ${c('ITEM')} fields. Behavior is spread across ${c('TRIGGER')} triggers and ${c('PROGRAM_UNIT')} program units. Select a rule or connection to inspect its source and proposed destination.</p><div class="bp-categories">${categories.map(([title,value,filter,description])=>bpFilterButton(filter,`<b>${value}</b><span>${title} ↗</span><small>${description}</small>`)).join('')}</div></section>
 <section class="bp-card"><div class="bp-eyebrow">Connected source</div><h3 style="margin-top:8px">Follow the application’s dependencies</h3><p class="bp-muted">Observed source connections. Select either end to inspect it; arrows do not imply execution order.</p><div style="margin-top:12px">${g.paths.length?bpRoutes(g.paths.slice(0,4)):'<p>No supported call or data-access paths were found. Inspect the components to understand the remaining scope.</p>'}</div>${g.paths.length>4?`<details><summary>Explore more connections (${g.paths.length} of ${g.path_total} shown)</summary>${bpRoutes(g.paths.slice(4))}</details>`:''}<div class="bp-actions" style="margin-top:14px"><button class="btn" data-bp-tab="inspect">Explore all components →</button></div></section>
 </div><aside class="bp-stack"><section class="bp-card bp-ai-card"><div class="bp-eyebrow">AI architecture companion</div><h3>Make sense of the application</h3><p>Get a guided explanation of the observed connections, modernization options and what to investigate next.</p><button class="btn primary" id="bp-ai-overview">Explain this application →</button><button class="btn" id="bp-ai-cancel" hidden>Discard request</button><button class="btn" id="bp-ai-save" hidden>Save AI briefing</button><p id="bp-ai-status" class="bp-ai-status" role="status" aria-live="polite"></p><div id="bp-ai-narrative"></div><small>${esc(d.ai_provider.label)} · AI proposals need your review.</small><details><summary>What is sent to AI?</summary><p class="bp-muted">Only component types, classifications and anonymized relationships. Source code, names and paths stay local. Closing this panel does not lose the running request.</p></details><button class="bp-link" id="bp-ai-settings" style="margin-top:10px">Change AI provider</button></section>
 <section class="bp-card"><div class="bp-section-title"><h3>Where to start</h3><span class="bp-chip">${g.code_pending} code units open</span></div><p class="bp-muted">Start with integrations and transactions, then candidate rules.</p><div class="bp-stack" style="margin-top:14px">${g.start_here.slice(0,4).map((n,i)=>`<button class="bp-row" data-bp-node="${esc(n.id)}"><span class="bp-index">${i+1}</span><span class="bp-row-text"><strong>${esc(n.name)}</strong><small>${esc(n.owner||n.module)} · ${esc(bpLabel(n.recommendation))}</small></span><span class="bp-arrow">→</span></button>`).join('')||'<p>No code decisions remain in this queue. You can still inspect every component.</p>'}</div><details><summary>How this list is ordered</summary><p class="bp-muted">${esc(g.reading_order)}</p></details></section></aside></div></div>
 <div id="bp-inspect" hidden><h3>Understand one component, then decide</h3><p class="bp-muted" style="margin-bottom:18px">Select a rule, trigger or dependency. Read why it matters before recording a decision.</p><div class="bp-filters"><label>Find a component<input id="bp-search" placeholder="Name of a form, trigger, package or table"></label><label>Component type<select id="bp-type">${bpOptions(d.options.types,'All components')}</select></label><label>Module<select id="bp-module"><option value="">All modules</option>${d.options.modules.map(m=>`<option value="${esc(m)}">${esc(m)}</option>`).join('')}</select></label></div><details><summary>Narrow by recommendation, review status or dependency</summary><div class="bp-extra-filters"><label>Recommendation<select id="bp-decision">${bpOptions(BP_DECISIONS,'All approaches')}</select></label><label>Review status<select id="bp-review">${bpOptions(['PENDING','APPROVE','MODIFY','REJECT','DEFER','STALE'],'All review states')}</select></label><label>Relationship<select id="bp-dependency">${bpOptions(d.options.dependencies,'All relationships')}</select></label><label>Domain hint<select id="bp-domain">${bpOptions(d.options.domains,'All domains')}</select></label><label>Measured risk<select id="bp-risk">${bpOptions(['LOW','MEDIUM','HIGH','CRITICAL'],'All levels')}</select></label><button class="btn" id="bp-clear">Clear filters</button></div></details><div id="bp-page" class="bp-page" role="status"></div><div class="bp-explorer"><div id="bp-list" class="bp-list"></div><section id="bp-detail" class="bp-card bp-detail"><div class="bp-empty"><h3>Choose a component to read its story</h3><p>Its source, relationships and recommendation will appear here.</p></div></section></div></div>
 <div id="bp-plan" hidden class="bp-stack"><section class="bp-card"><div class="bp-eyebrow">Proposed direction · requires your decision</div><h3 style="margin-top:8px">What could the modernized application look like?</h3><p class="bp-muted">These are architecture options from static analysis. They are not a deployed design.</p><div class="bp-target" style="margin-top:18px">${d.architecture.target.map(t=>`<section class="bp-card"><h4>${esc(t.name)}</h4><p>${esc(t.reason)}</p></section>`).join('')}</div></section>
 <div class="bp-two"><section class="bp-card"><h3>Suggested approaches</h3><p class="bp-muted">Select an approach to inspect its components. Counts include structural objects as well as code.</p><div class="bp-strategy">${Object.entries(d.summary.decisions).map(([k,v])=>bpFilterButton({decision:k},`<b>${v}</b><span class="bp-row-text"><strong>${esc(bpLabel(k))}</strong></span><span class="bp-arrow">→</span>`,'bp-row')).join('')}</div></section><section class="bp-card"><h3>Your architecture review</h3><p>${g.code_reviewed} of ${g.code_total} code units have an accepted or modified approach.</p><div class="bp-progress" role="img" aria-label="${g.code_reviewed} of ${g.code_total} code units reviewed"><span style="width:${accepted}%"></span></div><small>Architecture decisions do not mean the implementation is complete.</small><h4 style="margin-top:22px">Implementation coverage</h4><p style="margin-top:8px">${Object.entries(d.summary.coverage).map(([k,v])=>`${esc(bpLabel(k))}: <b>${v}</b>`).join('<br>')}</p><details><summary>Conversion progress and analysis limits</summary><p>Existing migration work progress: ${d.readiness.score}/100. ${esc(d.readiness.explanation.caveat)}</p><p>${d.catalog_coverage.unknown_trigger_units} of ${d.catalog_coverage.trigger_units} triggers have no catalog verdict.</p><pre>${esc(JSON.stringify(d.readiness,null,2))}</pre>${d.limitations.map(s=>`<p>${esc(s)}</p>`).join('')}</details></section></div>
 <section class="bp-card"><h3>Reusable API candidates</h3><p class="bp-muted">${d.api_candidate_total?`${d.api_candidate_total} repeated capabilities merit investigation. Reuse does not establish that exposing an API is appropriate.`:'No repeated cross-form qualified calls met the candidate criteria. A single form alone does not establish application-wide reuse.'}</p>${d.api_candidates.map(c=>`<div style="margin-top:12px"><button class="bp-link" data-bp-node="${esc(c.entity)}">Inspect capability →</button> · ${c.forms.length} forms · ${c.callers.length} callers<details><summary>Why it was selected</summary><p>${esc(c.formula)} = ${c.score}/${c.maximum}. Callee behavior still needs review.</p></details></div>`).join('')}</section>
 <section class="bp-card"><h3>Take the plan with you</h3><p class="bp-muted">Use the report for discussion and the structured export for engineering work.</p><div class="bp-actions" style="margin-top:14px"><a class="btn primary" href="/api/blueprint/report" target="_blank" rel="noopener">Open readable report ↗</a><button class="btn" id="bp-export">Save reports to disk</button><a class="btn" href="/api/blueprint/json" target="_blank" rel="noopener">Download analysis JSON</a></div><p id="bp-export-status" role="status"></p><details><summary>Enterprise naming hints</summary><p class="bp-muted">Naming hints do not establish an EBS installation.</p><pre>${esc(JSON.stringify(d.enterprise_context,null,2))}</pre></details></section></div>`;
}
function bpTab(tab,load=true){
 for(const t of ['understand','inspect','plan'])$('bp-'+t).hidden=t!==tab;
 document.querySelectorAll('[data-bp-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.bpTab===tab)));
 if(load&&tab==='inspect'&&!$('bp-list').children.length)bpExplore('',0);
 $('modal-body').scrollTop=0;
}
function bpFilter(values){for(const [key,id] of Object.entries(BP_FILTERS))$(id).value=values[key]||'';bpTab('inspect',false);bpExplore('',0);}
async function bpExplore(node='',offset=null){
 offset=offset===null?bpOffset:offset;bpOffset=offset;const request=++bpRequest,context=bpContext;
 const q=new URLSearchParams({node,offset,limit:40,context_id:context.d.context_id||''});for(const [key,id] of Object.entries(BP_FILTERS))q.set(key,$(id).value);
 $('bp-page').textContent='Loading components…';
 try{const r=await api('/api/blueprint/explore?'+q);if(request!==bpRequest||!bpAlive(context)||!$('bp-list'))return;
 $('bp-page').innerHTML=`<span>${r.total?`${offset+1}–${offset+r.nodes.length} of ${r.total} components`:'No components match these filters'}</span><div class="bp-actions"><button class="btn" id="bp-prev" ${offset<=0?'disabled':''}>← Previous</button><button class="btn" id="bp-next" ${offset+r.limit>=r.total?'disabled':''}>Next →</button></div>`;
 $('bp-prev').onclick=()=>bpExplore('',Math.max(0,offset-r.limit));$('bp-next').onclick=()=>bpExplore('',offset+r.limit);
 $('bp-list').innerHTML=r.nodes.map(n=>`<button class="bp-row" data-bp-node="${esc(n.id)}" aria-pressed="${n.id===node}"><strong>${esc(n.name)}</strong><small>${esc(bpLabel(n.type))} · ${esc(n.attributes.owner||n.module||'Shared dependency')}</small><small>${esc(bpLabel(n.review_state))}</small></button>`).join('')||'<p class="bp-muted">Try another name or clear the filters.</p>';
 if(r.selected){bpDetail(r.selected);$('bp-detail').scrollIntoView({block:'start'});}else {bpSelectedFinding='';$('bp-detail').innerHTML='<div class="bp-empty"><h3>Select a component</h3><p>See its observed connections, source evidence and suggested approach here.</p></div>';}
 }catch(e){if(request===bpRequest&&bpAlive(context))$('bp-page').textContent=e.message;}
}
function bpDetail(s){
 const n=s.entity,f=s.finding,nodes=Object.fromEntries(s.neighbors.map(n=>[n.id,n]));
 const context=bpContext;bpSelectedFinding=f?.entity||'';
 if(bpSelectedNode&&bpSelectedNode!==n.id){bpHistory.push(bpSelectedNode);if(bpHistory.length>30)bpHistory.shift();}bpSelectedNode=n.id;
 const links=(edges,inbound)=>edges.filter(e=>e.type!=='CONTAINS').slice(0,12).map(e=>`<span class="bp-chip">${esc(bpLabel(e.type))} ${bpNode(nodes[inbound?e.source:e.target]||{id:inbound?e.source:e.target,name:'Component'})}</span>`).join('')||(n.attributes.source_entity?`<p class="bp-muted">This candidate belongs to a source code unit. ${bpNode({id:n.attributes.source_entity,name:'Open its source unit and dependencies →'})}</p>`:'<p class="bp-muted">No non-structural relationships observed here.</p>');
 const proofs=s.evidence.map(p=>`<div class="bp-evidence"><small>${esc(bpLabel(p.level))} · ${esc(p.component)}${p.location?' · code line '+p.location.line:''}</small><pre>${esc(p.text)}</pre></div>`);
 $('bp-detail').innerHTML=`<div class="bp-detail-head"><button class="btn" id="bp-back" ${bpHistory.length?'':'disabled'}>← Previous component</button><span class="bp-draft" id="bp-draft-status"></span></div><div class="bp-eyebrow">${esc(bpLabel(n.type))}</div><h3 style="margin-top:8px">${esc(n.name)}</h3><p class="bp-muted">${esc(s.source_context?.owner||n.attributes.owner||'')} ${esc(n.module||'Shared across source references')}</p>
 ${f?`${f.human_decision?`<p><b>Your chosen approach:</b> ${esc(bpLabel(f.human_decision.recommendation))} · ${esc(f.human_decision.target)}</p>`:""}<div class="bp-recommendation"><div class="bp-eyebrow">Suggested approach · not yet an implementation</div><h4>${esc(bpLabel(f.recommendation))}</h4><p>${esc(f.reason)}</p><p style="margin-top:8px"><b>Possible destination:</b> ${esc(f.suggested_target)}</p><div>${(f.classification||[]).map(bpChip).join('')}</div></div>`:''}
 <h4 style="margin-top:18px">What this component connects to</h4><div class="bp-deps">${links(s.outbound,false)}</div><details><summary>Where it is used</summary><div class="bp-deps">${links(s.inbound,true)}</div></details>
 <h4 style="margin-top:20px">Why the analysis says this</h4>${s.source_context?.text?`<div class="bp-evidence"><div class="bp-code-tools"><small>Original PL/SQL · decoded source body${s.source_context.truncated?" · first 64,000 characters":""}</small><button class="btn" id="bp-copy-source">Copy source</button></div><pre>${esc(s.source_context.text)}</pre></div>`:""}${proofs.slice(0,3).join('')||'<p class="bp-muted">No source excerpt is available for this component.</p>'}${proofs.length>3?`<details><summary>Show ${proofs.length-3} more evidence excerpts</summary>${proofs.slice(3).join('')}</details>`:''}
 ${f?`<details><summary>Questions to resolve before implementation (${f.unresolved_questions.length})</summary>${f.unresolved_questions.map(q=>`<p>${esc(q)}</p>`).join('')||'<p>No additional questions were identified by these rules. Runtime behavior still requires validation.</p>'}${f.statements.map(x=>`<p><b>${esc(bpLabel(x.level))}:</b> ${esc(x.text)}</p>`).join('')}</details><div class="bp-actions" style="margin-top:20px"><button class="btn primary" id="bp-decide">Record my decision</button><button class="btn" id="bp-ai">Explain with AI</button><button class="btn" id="bp-unit-ai-cancel" hidden>Discard request</button>${bpChip(f.review_state||'PENDING')}</div><pre id="bp-ai-result" role="status"></pre>
 <section id="bp-review-form" class="bp-review-form" hidden><h4 style="margin-bottom:12px">What should happen to this component?</h4><label>Your decision<select id="bp-action">${bpOptions(['APPROVE','MODIFY','REJECT','DEFER'])}</select></label><div id="bp-modify-fields" hidden><label>Alternative approach<select id="bp-modify">${bpOptions(BP_DECISIONS)}</select></label><label>Proposed destination<input id="bp-target" value="${esc(f.suggested_target)}"></label></div><label>Reviewer<input id="bp-reviewer" value="${esc($('reviewer')?.value||'')}"></label><label>Why?<textarea id="bp-comment" maxlength="8000" placeholder="Record the reason so the next reviewer understands your decision."></textarea></label><details><summary>Also record implementation coverage (optional)</summary><p class="bp-muted">Only record completed work when you can point to implementation evidence.</p><label>Implementation status<select id="bp-coverage">${bpOptions(BP_COVERAGE)}</select></label><label>Change, test or implementation reference<textarea id="bp-coverage-evidence" maxlength="8000"></textarea></label></details><div class="bp-actions" style="margin-top:14px"><button class="btn primary" id="bp-save">Save decision</button><button class="btn" id="bp-cancel-review">Close form</button><button class="bp-link" id="bp-discard-draft">Discard unsaved changes</button></div><p role="status" id="bp-review-status"></p></section><details><summary>Previous decisions (${(f.review_history||[]).length})</summary>${(f.review_history||[]).map(r=>`<div class="bp-evidence"><b>${esc(bpLabel(r.action))}</b><p>${esc(r.comment||'')}</p><small>${esc(r.reviewer||'')} · ${esc(r.decided_at||'')}</small></div>`).join('')||'<p>No decisions recorded.</p>'}</details>`:''}
 <details><summary>Technical details</summary>${s.truncated?`<p>This view contains part of ${s.edge_total} relationships. Use the JSON report for the full graph.</p>`:''}<p>${s.evidence.length} of ${s.evidence_total} evidence excerpts shown.</p><pre>${esc(JSON.stringify(Object.fromEntries(Object.entries(n.attributes).filter(([k])=>k!=="source_text")),null,2))}</pre>${f?`<p>Migration execution verdict: ${esc(f.execution_verdict||'Not applicable')}</p>`:''}</details>`;
 $('bp-back').onclick=()=>{const previous=bpHistory.pop();if(previous){bpSelectedNode='';bpExplore(previous);}};
 if($('bp-copy-source'))$('bp-copy-source').onclick=async()=>{try{await navigator.clipboard.writeText(s.source_context.text);toast('Source copied.');}catch(_){toast('Clipboard unavailable. Select and copy the source text.',true);}};
 if(!f)return;
 const draftKey=bpDraftScope+'|'+f.entity+'|'+f.revision;
 const fieldIds=['bp-action','bp-modify','bp-target','bp-reviewer','bp-comment','bp-coverage','bp-coverage-evidence'];
 const values=bpDrafts.get(draftKey)||{'bp-action':'APPROVE','bp-modify':f.human_decision?.recommendation||f.recommendation,'bp-target':f.human_decision?.target||f.suggested_target,'bp-reviewer':$('reviewer')?.value||'','bp-comment':'','bp-coverage':f.coverage?.status||'REQUIRES_REVIEW','bp-coverage-evidence':f.coverage?.evidence||''};
 for(const id of fieldIds)$(id).value=values[id]||'';
 function markDraft(){if(!bpAlive(context))return;bpDrafts.set(draftKey,Object.fromEntries(fieldIds.map(id=>[id,$(id).value])));$('bp-draft-status').textContent='Unsaved decision · kept in this tab';}
 for(const id of fieldIds)$(id).addEventListener('input',markDraft);
 $('bp-modify-fields').hidden=$('bp-action').value!=='MODIFY';
 if(bpDrafts.has(draftKey)){$('bp-draft-status').textContent='Unsaved decision restored';$('bp-review-form').hidden=false;}
 $('bp-decide').onclick=()=>{$('bp-review-form').hidden=false;$('bp-action').focus();};
 $('bp-cancel-review').onclick=()=>{$('bp-review-form').hidden=true;$('bp-decide').focus();};
 $('bp-discard-draft').onclick=()=>{bpDrafts.delete(draftKey);bpDetail(s);};
 $('bp-action').onchange=()=>{$('bp-modify-fields').hidden=$('bp-action').value!=='MODIFY';markDraft();};
 $('bp-save').onclick=async()=>{
  const button=$('bp-save'),status=$('bp-review-status');
  if(!$('bp-reviewer').value.trim()||!$('bp-comment').value.trim()){status.textContent='Add your name and the reason for this decision.';(!$('bp-reviewer').value.trim()?$('bp-reviewer'):$('bp-comment')).focus();return;}
  button.disabled=true;status.textContent='Saving decision…';
  const submitted=JSON.stringify(Object.fromEntries(fieldIds.map(id=>[id,$(id).value])));
  const body={context_id:context.d.context_id,entity:f.entity,revision:f.revision,action:$('bp-action').value,recommendation:$('bp-modify').value,target:$('bp-target').value,reviewer:$('bp-reviewer').value,comment:$('bp-comment').value,coverage:$('bp-coverage').value,coverage_evidence:$('bp-coverage-evidence').value};
  try{await api('/api/blueprint/review',body);if(JSON.stringify(bpDrafts.get(draftKey))===submitted)bpDrafts.delete(draftKey);if(bpAlive(context)&&bpSelectedNode===n.id){await showBlueprint(n.id);toast(bpDrafts.has(draftKey)?'Decision saved. Your newer edits are still unsaved.':'Architecture decision saved.');}}
  catch(e){if(bpAlive(context)&&bpSelectedNode===n.id){status.textContent=e.message;button.disabled=false;}}
 };
 $('bp-ai').onclick=()=>bpStartAI('entity',f.entity);
 $('bp-unit-ai-cancel').onclick=()=>bpCancelAI('entity',f.entity);
 bpResumeAI('entity',f.entity);
}

function bpRenderAdvisory(result){
 bpAdvisory=result;
 $('bp-ai-narrative').innerHTML=result.sections.map((s,i)=>`<details class="bp-ai-section" ${i===0?'open':''}><summary>${esc(s.title)}</summary><p>${esc(s.text)}</p><div class="bp-deps">${s.components.map(bpNode).join(' · ')}</div></details>`).join('');
 $('bp-ai-save').hidden=false;$('bp-ai-overview').textContent='Refresh AI explanation';
}
function bpAIElements(scope){return scope==='application'?{button:$('bp-ai-overview'),status:$('bp-ai-status'),cancel:$('bp-ai-cancel')}:{button:$('bp-ai'),status:$('bp-ai-result'),cancel:$('bp-unit-ai-cancel')};}
function bpAIVisible(context,scope,entity){return bpAlive(context)&&(scope==='application'||bpSelectedFinding===entity);}
function bpAIStatus(job,context,scope,entity){
 if(!bpAIVisible(context,scope,entity))return;
 const elements=bpAIElements(scope);if(!elements.button||!elements.status)return;
 const running=job.status==='running';elements.button.disabled=running;
 elements.status.dataset.running=String(running);elements.status.setAttribute('aria-busy',String(running));
 if(elements.cancel){elements.cancel.hidden=!running;elements.cancel.dataset.job=job.job_id||'';}
 if(running){
  const seconds=Math.max(0,Math.floor(job.elapsed_seconds||0));
  const elapsed=seconds>=60?`${Math.floor(seconds/60)}m ${seconds%60}s`:`${seconds}s`;
  elements.status.textContent=`AI request in progress · ${elapsed}. You can continue reviewing or close this panel; the result will be here when you return.`;
 }else if(job.status==='completed'&&job.result){
  if(scope==='application'){bpRenderAdvisory(job.result);elements.status.textContent='AI proposal ready. Review the linked components before acting.';}
  else elements.status.textContent='AI proposal — review before acting\n\n'+job.result.text;
 }else if(job.status==='failed')elements.status.textContent=job.error||'The AI request failed. Check the provider and retry.';
 else if(job.status==='cancelled')elements.status.textContent='Result discarded. The provider may finish in the background; another request can start after it settles.';
 else if(job.status==='stale')elements.status.textContent='The source or provider changed. Start a new explanation for the current analysis.';
 else elements.status.textContent='';
}
async function bpResumeAI(scope,entity='',jobId='',context=bpContext){
 if(!bpAIVisible(context,scope,entity))return;
 const key=scope==='application'?scope:'entity';clearTimeout(bpPolls.get(key));
 const request=(bpAIRequests.get(key)||0)+1;bpAIRequests.set(key,request);
 const q=new URLSearchParams(scope==='application'?{scope}:{entity});if(jobId)q.set('job_id',jobId);q.set('context_id',context.d.context_id||'');
 try{
  const job=await api('/api/blueprint/ai?'+q);if(request!==bpAIRequests.get(key)||!bpAIVisible(context,scope,entity))return;
  bpAIStatus(job,context,scope,entity);
  if(job.status==='running')bpPolls.set(key,setTimeout(()=>bpResumeAI(scope,entity,job.job_id,context),1500));
 }catch(e){if(request===bpAIRequests.get(key)&&bpAIVisible(context,scope,entity)){const elements=bpAIElements(scope);elements.status.textContent=e.message+' Reopen Blueprint to reconnect.';elements.button.disabled=false;}}
}
async function bpStartAI(scope,entity=''){
 const context=bpContext,elements=bpAIElements(scope);elements.button.disabled=true;elements.status.textContent='Starting AI request…';
 const key=scope==='application'?scope:'entity',request=(bpAIRequests.get(key)||0)+1;bpAIRequests.set(key,request);clearTimeout(bpPolls.get(key));
 try{
  const job=await api('/api/blueprint/ai',{background:true,scope,entity,source_revision:context.d.source_revision,context_id:context.d.context_id,refresh:true});
  if(request!==bpAIRequests.get(key)||!bpAIVisible(context,scope,entity))return;
  bpAIStatus(job,context,scope,entity);
  if(job.status==='running')await bpResumeAI(scope,entity,job.job_id,context);
 }catch(e){if(request===bpAIRequests.get(key)&&bpAIVisible(context,scope,entity)){elements.status.textContent=e.message;elements.button.disabled=false;}}
}
async function bpCancelAI(scope,entity=''){
 const context=bpContext,elements=bpAIElements(scope),jobId=elements.cancel?.dataset.job;
 if(!jobId)return;elements.cancel.disabled=true;
 const key=scope==='application'?scope:'entity',request=(bpAIRequests.get(key)||0)+1;bpAIRequests.set(key,request);clearTimeout(bpPolls.get(key));
 try{const job=await api('/api/blueprint/ai/cancel',{job_id:jobId,context_id:context.d.context_id});if(request===bpAIRequests.get(key)&&bpAIVisible(context,scope,entity))bpAIStatus(job,context,scope,entity);}
 catch(e){if(request===bpAIRequests.get(key)&&bpAIVisible(context,scope,entity)){elements.status.textContent=e.message;bpPolls.set(key,setTimeout(()=>bpResumeAI(scope,entity,jobId,context),2000));}}
 finally{if(request===bpAIRequests.get(key)&&bpAIVisible(context,scope,entity))elements.cancel.disabled=false;}
}
function bpSaveBriefing(d){
 const result=bpAdvisory;if(!result)return;
 const body='<!doctype html><html lang="en"><meta charset="utf-8"><title>FormsLang AI briefing</title><style>body{font:16px system-ui;max-width:850px;margin:40px auto;padding:20px;line-height:1.7}section{border-top:1px solid #ddd;margin-top:24px}p{white-space:pre-wrap}</style><h1>'+esc(d.application.name)+'</h1><p>AI proposal — not an approved architecture or verified runtime behavior.</p><p>Provider: '+esc(d.ai_provider.label)+'<br>Source revision: '+esc(d.source_revision)+'</p>'+result.sections.map(s=>'<section><h2>'+esc(s.title)+'</h2><p>'+esc(s.text)+'</p><small>Components: '+s.components.map(n=>esc(n.name)).join(', ')+'</small></section>').join('')+'</html>';
 const url=URL.createObjectURL(new Blob([body],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='formslang-ai-briefing.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
"""
