"""Modernization inside the existing Workbench; no new app or frontend build."""

BLUEPRINT_JS = r"""
let bpRequest = 0;
let bpOffset = 0;
const BP_DECISIONS = ['PRESERVE','CONVERT','REFACTOR','WRAP_AS_API','DROP','MANUAL_REVIEW','UNKNOWN'];
const BP_COVERAGE = ['REQUIRES_REVIEW','PRESERVED','CONVERTED','REFACTORED','DROPPED_INTENTIONALLY','UNSUPPORTED','UNKNOWN'];
const bpOptions = (values, first) => (first ? `<option value="">${esc(first)}</option>` : '') + values.map(v => `<option value="${esc(v)}">${esc(v)}</option>`).join('');

async function showBlueprint(selectedNode='') {
  const filters = selectedNode ? Object.fromEntries(['bp-module','bp-type','bp-dependency','bp-decision','bp-review','bp-domain','bp-risk','bp-search'].map(id=>[id,$(id)?.value||''])) : {};
  let data;
  try { data = await api('/api/blueprint'); } catch(e) { toast(e.message, true); return; }
  openModal('Modernization Blueprint');
  $('modal-path').textContent = data.available ? data.application.name : 'Application knowledge · architecture · human review';
  $('modal-hint').textContent = 'Local deterministic analysis. Facts, inferences, assumptions and unknowns remain distinct. Coverage records human declarations; runtime parity is not verified.';
  foot(null);
  $('modal-body').innerHTML = `<style>
    .sheet:has(#bp){width:min(1250px,96vw)}
    #bp{display:grid;gap:20px;padding:0 16px}#bp h3{margin:0 0 10px}#bp p{line-height:1.5}
    .bp-tools,.bp-filters{display:flex;gap:8px;flex-wrap:wrap;align-items:end}
    #bp label{display:grid;gap:5px;font-size:12px;color:var(--ink-dim);max-width:100%}
    #bp input,#bp select,#bp textarea{padding:8px;border:1px solid var(--line);border-radius:5px;background:var(--panel);color:var(--ink);max-width:100%;min-width:0}
    #bp textarea{width:100%;min-height:64px}#bp pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:330px;overflow:auto}
    .bp-grid{display:grid;grid-template-columns:minmax(230px,1fr) minmax(300px,2fr);gap:16px}
    .bp-list{max-height:570px;overflow:auto}.bp-list button{display:block;text-align:left;width:100%;margin-bottom:5px;white-space:normal}
    .bp-card{padding:16px;border:1px solid var(--line);border-radius:9px}.bp-kpis{display:flex;gap:20px;flex-wrap:wrap}.bp-kpis b{font-size:24px;display:block}
    .bp-detail{min-width:0}.bp-evidence{border-left:3px solid #f5a640;padding:6px 10px;margin:8px 0}.bp-detail details{margin:12px 0}
    @media(max-width:760px){.bp-grid{grid-template-columns:1fr}}
    </style><div id="bp">
      <div class="bp-tools"><label>Application directory (optional)<input id="bp-source" placeholder="Blank = open module"></label>
        <label><span>Enterprise context</span><input type="checkbox" id="bp-enterprise" ${data.available && data.enterprise_context.enabled ? 'checked' : ''}></label>
        <button class="btn primary" id="bp-build">${data.available ? 'Regenerate from source' : 'Analyze locally'}</button>
        ${data.available ? '<button class="btn" id="bp-export">Write artifacts</button><a class="btn" href="/api/blueprint/report" target="_blank" rel="noopener">HTML report</a><a class="btn" href="/api/blueprint/json" target="_blank" rel="noopener">Full JSON</a>' : ''}
      </div><div id="bp-status" role="status"></div>
      ${data.available ? bpOverview(data) : '<p>Open a Forms module, enter an application directory, or open a Blueprint session generated by the CLI. No AI provider is required.</p>'}
    </div>`;
  $('bp-build').onclick = async () => {
    const button = $('bp-build');button.disabled=true;$('bp-status').textContent='Analyzing source and dependencies locally…';
    try {await api('/api/blueprint/build',{path:$('bp-source').value,enterprise:$('bp-enterprise').checked});await refresh();await showBlueprint();}
    catch(e){$('bp-status').textContent=e.message;button.disabled=false;}
  };
  if (!data.available) return;
  for(const [id,value] of Object.entries(filters))$(id).value=value;
  $('bp-export').onclick = async () => {try {const r=await api('/api/blueprint/export',{});$('bp-status').textContent='Artifacts written to '+r.path;} catch(e){toast(e.message,true);}};
  for(const id of ['bp-module','bp-type','bp-dependency','bp-decision','bp-review','bp-domain','bp-risk']) $(id).onchange=()=>bpExplore('',0);
  let searchTimer;
  $('bp-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>bpExplore('',0),200);};
  $('bp').addEventListener('click',e=>{const node=e.target.closest('[data-bp-node]');if(node)bpExplore(node.dataset.bpNode);});
  await bpExplore(selectedNode,0);
}

function bpOverview(d) {
  const count = type => d.summary.entities[type] || 0;
  const kpis = [['Forms',count('FORM')],['Blocks',count('BLOCK')],['Items',count('ITEM')],['Triggers',count('TRIGGER')],['Program units',count('PROGRAM_UNIT')],['Package references',count('PACKAGE_REFERENCE')],['Dependency edges',d.summary.dependency_edges],['Resolved integrations',count('INTEGRATION_POINT')],['Rule candidates',count('BUSINESS_RULE')],['API candidates',d.api_candidate_total]];
  return `<section class="bp-card"><h3>Application knowledge</h3><div class="bp-kpis">${kpis.map(([k,v])=>`<div><b>${v}</b>${esc(k)}</div>`).join('')}</div>
    ${d.stale_engine ? '<p><strong>Analysis engine changed. Regenerate before reviewing.</strong></p>' : ''}
    ${d.failures.length ? `<p><strong>Incomplete application: ${d.failures.length} source(s) failed.</strong></p><pre>${esc(JSON.stringify(d.failures,null,2))}</pre>` : ''}</section>
    <section class="bp-card"><h3>Modernization strategy · recommendations</h3><p>${Object.entries(d.summary.decisions).map(([k,v])=>`${esc(k)} <b>${v}</b>`).join(' · ')}</p>
      <p>Modernization coverage: ${Object.entries(d.summary.coverage).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')}</p>
      <p>Human review: ${Object.entries(d.summary.review).map(([k,v])=>`${esc(k)} ${v}`).join(' · ')}</p></section>
    <section class="bp-card"><h3>Migration work progress · ${d.readiness.score}/100</h3><p>${esc(d.readiness.explanation.caveat)}</p><p>${esc(d.readiness.scope)}</p>
      <p>Catalog debt: ${d.catalog_coverage.unknown_trigger_units}/${d.catalog_coverage.trigger_units} trigger units have unknown verdicts; ${d.catalog_coverage.uncatalogued_invocations} uncatalogued invocations.</p><small>${esc(d.catalog_coverage.note)}</small>
      <details><summary>Inspect the readiness calculation (${esc(d.readiness.version)})</summary><pre>${esc(JSON.stringify(d.readiness,null,2))}</pre></details></section>
    <details class="bp-card"><summary>Current and proposed architecture</summary>
      <h4>FACT · Observed current components</h4>${d.architecture.current.map(g=>`<p>${esc(g.name)}: ${g.entities.length} entities</p>`).join('')}
      <h4>INFERENCE · Proposed target</h4>${d.architecture.target.map(g=>`<p><b>${esc(g.name)}</b> — ${esc(g.reason)}</p>`).join('')}
      ${d.architecture.assumptions.concat(d.architecture.unknowns).map(s=>`<p><b>${esc(s.level)}</b> ${esc(s.text)}</p>`).join('')}</details>
    <details class="bp-card"><summary>API candidates · reuse priority, not safety (${d.api_candidate_total})</summary><p>No endpoints are generated. Callee behavior and transaction ownership require review.</p>
      ${d.api_candidates.map(c=>`<p><button class="btn" data-bp-node="${esc(c.entity)}">Inspect candidate</button> ${c.forms.length} Forms · ${c.callers.length} callers · ${c.score}/${c.maximum}<br><small>${esc(c.formula)} · ${esc(JSON.stringify(c.components))}</small></p>`).join('')}
      ${d.api_candidate_total>d.api_candidates.length ? '<p>First 30 candidates shown; full ranking in JSON.</p>' : ''}</details>
    <details class="bp-card"><summary>Enterprise patterns and analysis limits</summary><pre>${esc(JSON.stringify(d.enterprise_context,null,2))}</pre>${d.limitations.map(x=>`<p>${esc(x)}</p>`).join('')}</details>
    <section><h3>Dependency explorer</h3><div class="bp-filters">
      <label>Name<input id="bp-search" placeholder="Search entities"></label>
      <label>Module<select id="bp-module">${bpOptions(d.options.modules,'All modules')}</select></label>
      <label>Entity<select id="bp-type">${bpOptions(d.options.types,'All types')}</select></label>
      <label>Dependency<select id="bp-dependency">${bpOptions(d.options.dependencies,'All relationships')}</select></label>
      <label>Decision<select id="bp-decision">${bpOptions(BP_DECISIONS,'All recommendations')}</select></label>
      <label>Review<select id="bp-review">${bpOptions(['PENDING','APPROVE','MODIFY','REJECT','DEFER','STALE'],'All review states')}</select></label>
      <label>Potential domain<select id="bp-domain">${bpOptions(d.options.domains,'All domains')}</select></label>
      <label>Measured risk<select id="bp-risk">${bpOptions(['LOW','MEDIUM','HIGH','CRITICAL'],'All risk levels')}</select></label>
      </div><p id="bp-page" role="status"></p><div class="bp-grid"><div class="bp-list" id="bp-list"></div><div class="bp-detail bp-card" id="bp-detail">Select an entity to inspect its evidence and dependencies.</div></div></section>`;
}

async function bpExplore(node='',offset=null) {
  offset=offset===null?bpOffset:offset;bpOffset=offset;
  const request=++bpRequest;
  const q=new URLSearchParams({node,offset,limit:80});
  for(const [key,id] of Object.entries({module:'bp-module',entity_type:'bp-type',dependency_type:'bp-dependency',decision:'bp-decision',review:'bp-review',domain:'bp-domain',risk_level:'bp-risk',query:'bp-search'}))q.set(key,$(id).value);
  try {
    const result=await api('/api/blueprint/explore?'+q);
    if(request!==bpRequest || !$('bp-list'))return;
    $('bp-page').innerHTML=`Showing ${result.nodes.length} of ${result.total} matching entities <button class="btn" id="bp-prev" ${offset<=0?'disabled':''}>Previous</button> <button class="btn" id="bp-next" ${offset+result.limit>=result.total?'disabled':''}>Next</button>`;
    $('bp-prev').onclick=()=>bpExplore('',Math.max(0,offset-result.limit));$('bp-next').onclick=()=>bpExplore('',offset+result.limit);
    $('bp-list').innerHTML=result.nodes.map(n=>`<button class="btn" data-bp-node="${esc(n.id)}"><b>${esc(n.name)}</b><br><small>${esc(n.type)} · ${esc(n.module || 'shared reference')} · ${esc(n.review_state)}</small></button>`).join('');
    if(result.selected)bpDetail(result.selected);
  } catch(e){toast(e.message,true);}
}

function bpDetail(s) {
  const n=s.entity,f=s.finding,names=Object.fromEntries(s.neighbors.map(n=>[n.id,n.name]));
  const links=(edges,inbound)=>edges.map(e=>`<p>${esc(e.type)} · ${esc(e.level)} <button class="btn" data-bp-node="${esc(inbound?e.source:e.target)}">${esc(names[inbound?e.source:e.target]||'entity')}</button></p>`).join('') || '<p>None observed in this neighborhood.</p>';
  $('bp-detail').innerHTML=`<h3>${esc(n.name)}</h3><p>${esc(n.type)} · ${esc(n.module || 'shared reference')}</p>
    ${f ? `<p><b>Recommendation · INFERENCE: ${esc(f.recommendation)}</b></p><p>${esc(f.reason)}</p><p>Proposed target: ${esc(f.suggested_target)}</p>
      <p>Execution verdict: ${esc(f.execution_verdict||'not applicable')} · Review: ${esc(f.review_state||'PENDING')}</p>
      ${f.statements.map(x=>`<p><b>${esc(x.level)}</b> ${esc(x.text)}</p>`).join('')}
      <details open><summary>Unresolved questions</summary>${f.unresolved_questions.map(x=>`<p>${esc(x)}</p>`).join('')}</details>` : ''}
    <details open><summary>Source evidence (${s.evidence.length}/${s.evidence_total})</summary>${s.evidence.map(p=>`<div class="bp-evidence"><b>${esc(p.level)}</b> ${esc(p.source)} · ${esc(p.component)}${p.location?' · body line '+p.location.line:''}<pre>${esc(p.text)}</pre></div>`).join('')}</details>
    <details><summary>Inbound dependencies</summary>${links(s.inbound,true)}</details><details><summary>Outbound dependencies</summary>${links(s.outbound,false)}</details>
    ${s.truncated?`<p>Neighborhood truncated (${s.edge_total} edges). Full graph is available in JSON.</p>`:''}
    <details><summary>Measured attributes</summary><pre>${esc(JSON.stringify(n.attributes,null,2))}</pre></details>
    ${f ? `<h4>Human architecture decision</h4><label>Action<select id="bp-action">${bpOptions(['APPROVE','MODIFY','REJECT','DEFER'])}</select></label>
      <label>Modified recommendation<select id="bp-modify">${bpOptions(BP_DECISIONS)}</select></label>
      <label>Modified target<input id="bp-target" value="${esc(f.suggested_target)}"></label>
      <label>Reviewer<input id="bp-reviewer" value="${esc($('reviewer').value)}"></label><label>Rationale<textarea id="bp-comment"></textarea></label>
      <h4>Modernization coverage (separate from approval)</h4><label>Declared outcome<select id="bp-coverage">${bpOptions(BP_COVERAGE)}</select></label>
      <label>Implementation evidence / test or change reference<textarea id="bp-coverage-evidence"></textarea></label>
      <p><button class="btn primary" id="bp-save">Save human decision</button></p><div role="status" id="bp-review-status"></div>
      <details><summary>Review history</summary><pre>${esc(JSON.stringify(f.review_history||[],null,2))}</pre></details>
      <h4>Optional AI reviewer</h4><p>Send only anonymized component types, dependency counts, classification and recommendation to the configured provider (${esc(state.provider)}). Source text, names, literals and review comments are excluded. The answer remains an unapproved proposal.</p>
      <button class="btn" id="bp-ai">Request advisory explanation</button><pre id="bp-ai-result"></pre>` : ''}`;
  if(!f)return;
  $('bp-modify').value=f.recommendation;
  $('bp-save').onclick=async()=>{
    const button=$('bp-save');button.disabled=true;
    try{await api('/api/blueprint/review',{entity:f.entity,revision:f.revision,action:$('bp-action').value,recommendation:$('bp-modify').value,target:$('bp-target').value,reviewer:$('bp-reviewer').value,comment:$('bp-comment').value,coverage:$('bp-coverage').value,coverage_evidence:$('bp-coverage-evidence').value});await showBlueprint(n.id);}
    catch(e){$('bp-review-status').textContent=e.message;button.disabled=false;}
  };
  $('bp-ai').onclick=async()=>{
    const button=$('bp-ai'),output=$('bp-ai-result');button.disabled=true;output.textContent='Requesting an advisory proposal…';
    try{const r=await api('/api/blueprint/ai',{entity:f.entity});output.textContent='UNAPPROVED AI PROPOSAL\n\n'+r.text;}
    catch(e){output.textContent=e.message;}finally{button.disabled=false;}
  };
}
"""
