"""Oracle APEX 26.1 APEXlang artifact generation.

The workbench review database is the audit trail.  This module turns the
approved part of that trail into a real APEXlang application project, using
the starter generated by SQLcl 26.1 as its immutable base.  The generated
ZIP contains only APEX application artifacts; the human-review JSON and the
flat PL/SQL file stay beside it so they cannot confuse the APEX compiler.

The page itself follows the Forms screen: :mod:`formslang.apexlayout` turns
canvas, frame and item geometry into a tree of regions on Universal Theme's
12-column grid, and this module writes that tree with the APEXlang
vocabulary that ``apex validate`` accepted on a real 26.1 database.

An export is a pure function of the session: the same approved work, the
same deployment choices, the same bytes -- ZIP included. That is what makes
the APEXlang project something a team can commit, diff and rebuild in CI
(see docs/ci-cd.md) instead of a one-off download. The only value that is
not derived from the session is the application's session-state checksum
salt, which APEX needs to be unpredictable; it is drawn once per session
and then kept (:func:`checksum_salt`).
"""

from __future__ import annotations

import html
import json
import re
import secrets
import shutil
import tempfile
import unicodedata
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path

from .apexlayout import (
    Grid,
    PageLayout,
    Placed,
    RegionNode,
    StaticLov,
    build_layout,
    forms_caption,
    item_box,
)
from .model import FormModule, Item
from .store import APPROVED, Store

MMD_VERSION = "26.1.0+3102"
_TEMPLATE = Path(__file__).with_name("templates") / "apexlang26"
_SAFE_ALIAS = re.compile(r"^[a-z][a-z0-9-]{0,79}$")

#: Session settings (``Store.setting``) this module owns.
SETTING_SALT = "apex_checksum_salt"
SETTING_EXPORT_CONFIG = "apex_export_config"

#: Every ZIP entry carries this timestamp, so the archive depends on the
#: project's bytes alone and never on the clock it was built at.
_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)


def slug(value: str, *, fallback: str = "formslang-app") -> str:
    """A filesystem-safe APEX alias and human-readable component id."""
    ascii_text = unicodedata.normalize("NFKD", value or "").encode("ascii", "ignore").decode()
    text = re.sub(r"[^a-z0-9]+", "-", ascii_text.strip().lower()).strip("-")
    if not text or not text[0].isalpha():
        text = f"app-{text}" if text else fallback
    return text[:80].rstrip("-")


def _text(value: str, limit: int = 255) -> str:
    """Quote a one-line APEXlang string using JSON's compatible escaping."""
    clean = " ".join(str(value or "").split())[:limit]
    return json.dumps(clean, ensure_ascii=False)


def _fence(value: str, language: str = "") -> str:
    text = str(value or "").replace("\r\n", "\n").replace("\r", "\n").rstrip()
    if "```" in text:
        raise ValueError("approved code contains a triple-backtick fence")
    indented = "\n".join(f"                {line}" for line in text.split("\n"))
    return f"```{language}\n{indented}\n                ```"


def _write_lf(path: Path, text: str) -> None:
    """Write compiler-facing APEXlang files without Windows CRLF translation."""
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


@dataclass(frozen=True)
class ApexExportConfig:
    """Deployment choices. Workspace and schema may be resolved at import."""

    app_id: int = 100
    name: str = ""
    alias: str = ""
    workspace: str = ""
    schema: str = ""
    page: int = 1

    @classmethod
    def from_dict(cls, raw: dict | None, module: FormModule) -> ApexExportConfig:
        raw = raw or {}
        try:
            app_id = int(raw.get("app_id") or 100)
            page = int(raw.get("page") or 1)
        except (TypeError, ValueError):
            raise ValueError("application id and page must be integers") from None
        if not 1 <= app_id <= 9_999_999_999:
            raise ValueError("application id must be between 1 and 9999999999")
        if not 1 <= page <= 9_999_999_999 or page == 9999:
            raise ValueError("page must be a positive number other than 9999")

        alias = (raw.get("alias") or slug(module.name)).strip().lower()
        if not _SAFE_ALIAS.fullmatch(alias):
            raise ValueError("alias must start with a letter and use only a-z, 0-9 and hyphen")
        name = " ".join((raw.get("name") or module.title or module.name).split())[:255]
        if not name:
            raise ValueError("application name is required")
        workspace = " ".join(str(raw.get("workspace") or "").split())[:255]
        schema = " ".join(str(raw.get("schema") or "").split())[:128].upper()
        return cls(app_id, name, alias, workspace, schema, page)


@dataclass(frozen=True)
class ApexExportResult:
    project: Path
    zip_path: Path
    sql_path: Path
    json_path: Path
    manifest_path: Path
    approved: int

    def to_dict(self) -> dict:
        return {
            "project": str(self.project),
            "zip": str(self.zip_path),
            "sql": str(self.sql_path),
            "json": str(self.json_path),
            "manifest": str(self.manifest_path),
            "approved": self.approved,
            "format": "APEXlang 26.1",
        }


def checksum_salt(store: Store) -> str:
    """The session-state checksum salt every export of this session shares.

    APEX signs URLs with it, so it must be unpredictable: drawn once from
    the OS CSPRNG. But it is also the only byte of an export that is not
    derived from the session, so it is drawn *once* -- a re-export of the
    same approved work must produce the same ``application.apx``, or no
    diff of two exports would ever be clean.
    """
    salt = store.setting(SETTING_SALT)
    if not salt:
        salt = secrets.token_hex(32).upper()
        store.set_setting(SETTING_SALT, salt)
    return salt


def last_export_config(store: Store) -> dict:
    """The deployment choices the previous export used, or ``{}``.

    Shared by the workbench dialog (pre-filled) and ``formslang export``
    (defaults), so a command line reproduces the last click by default.
    """
    try:
        raw = json.loads(store.setting(SETTING_EXPORT_CONFIG) or "{}")
    except ValueError:
        return {}
    return raw if isinstance(raw, dict) else {}


def _application(config: ApexExportConfig, salt: str) -> str:
    return f"""app {config.alias.upper()} (
    name: {_text(config.name)}
    logo {{
        type: text
        text: &APP_TITLE.
    }}
    navigation {{
        homeUrl: {{
            page: {config.page}
        }}
        loginUrl: {{
            page: LOGIN
        }}
    }}
    navigationMenu {{
        listTemplate: @/side-navigation-menu
        templateOptions: [
            #DEFAULT#
            js-defaultCollapsed
            js-navCollapsed--hidden
            t-TreeNav--styleA
        ]
        list: @navigation-menu
    }}
    navigationBar {{
        list: @navigation-bar
        listTemplate: @/navigation-bar
        templateOptions: #DEFAULT#
    }}
    userInterface {{
        currentTheme: @universal-theme
        globalPage: 0
        addBuiltWithApexToFooter: false
    }}
    authentication {{
        scheme: @oracle-apex-accounts
    }}
    sessionStateProtection {{
        checksumSalt: {salt}
    }}
    runtime {{
        allowFeedback: true
        compatibilityMode: "26.1"
    }}
)
"""


def _deployment(config: ApexExportConfig) -> str:
    app: dict = {"id": config.app_id}
    if config.schema:
        app["databaseSession"] = {"parsingSchema": config.schema}
    data: dict = {"app": app}
    if config.workspace:
        data["workspace"] = {"name": config.workspace}
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _item_type(item: Item) -> str:
    """The native APEX item type a Forms item becomes.

    Every keyword here was accepted by ``apex validate`` on APEX 26.1: a
    List Item is a ``selectList`` and a Radio Group a ``radioGroup``, each
    fed by a shared static LOV built from the choices the .fmb declares. A
    Text Item declared ``MultiLine`` is a ``textarea`` -- the same verified
    keyword an editor item already used.

    Date and Number items deliberately stay ``textField``: the native date
    picker and number field keywords have not yet been proven against a
    live ``apex validate``, and one unknown keyword fails the whole import.
    Format masks and data types survive in the item comment either way.
    """
    kind = item.item_type.lower()
    if "display" in kind:
        return "displayOnly"
    if "editor" in kind or "area" in kind:
        return "textarea"
    if "check" in kind:
        return "checkbox"
    if "radio" in kind:
        return "radioGroup"
    if "list" in kind:
        return "selectList"
    return "textarea" if item.multi_line else "textField"


def _label_template(item: Item, kind: str, *, side: str | None = None, label_span: int = 0) -> str:
    """Which Universal Theme label template reproduces the Forms caption.

    ``side`` is where Forms draws it, as :func:`formslang.apexlayout.forms_caption`
    reads it (read from the item when not given). A prompt left of the field
    -- Start, the default edge -- is a label left of the field (``optional``
    or ``required``, with ``labelColumnSpan`` giving it the room the prompt
    took); one on the top edge is a label above. Universal Theme has no
    label right of or below a field, so those float inside it, as does a
    check box's caption (the control is the label). No caption at all --
    nothing on the screen, or a ``Hidden`` prompt display style -- hides the
    label rather than inventing one. A left label whose row was too crowded
    to leave it a ``labelColumnSpan`` (:func:`formslang.apexlayout._reconcile_label`
    zeroes it out rather than emit ``labelColumnSpan >= columnSpan``, which
    APEX rejects at render time) floats instead of losing its room entirely.
    """
    if side is None:
        side = forms_caption(item)[1]
    if side == "none":
        return "hidden"
    required = item.required and kind != "displayOnly"
    base = "required" if required else "optional"
    if kind == "checkbox" or side == "control":
        return f"{base}-floating"
    if side == "above":
        return f"{base}-above"
    if side == "left":
        return base if label_span else f"{base}-floating"
    return f"{base}-floating"


def _bool(value: bool) -> str:
    return "true" if value else "false"


def _grid_lines(grid: Grid) -> str:
    """The layout keywords that put a box on the 12-column grid."""
    lines = [f"startNewRow: {_bool(grid.new_row)}"]
    if grid.flow:
        if not grid.new_row:
            lines.append("newColumn: false")
    else:
        if not grid.new_row:
            lines.append(f"newColumn: {_bool(grid.new_column)}")
        if grid.new_row or grid.new_column:
            lines.append(f"column: {grid.column}")
            lines.append(f"columnSpan: {grid.span}")
    return "".join(f"\n            {line}" for line in lines)


def _where(placed: Placed, layout: PageLayout) -> str:
    item = placed.item
    x, y, w, h = item_box(item)
    unit = layout.unit or "unit"
    caption = {
        "left": "prompt left of the field",
        "right": "prompt right of the field",
        "above": "prompt above the field",
        "below": "prompt below the field",
        "control": "caption on the control itself",
        "none": "prompt hidden" if placed.caption else "no caption shown",
    }[placed.side]
    return (
        f"Forms canvas {item.canvas}, position ({x:g}, {y:g}), size {w:g}x{h:g} "
        f"{unit.lower()}s, {caption}"
    )


def _static_html(node: RegionNode) -> str:
    """Boilerplate text as the HTML a static region shows: one paragraph,
    line breaks kept, nothing that could read as markup or close the fence."""
    lines = [
        html.escape(" ".join(line.split())) for line in node.text.splitlines() if line.strip()
    ]
    body = "<br>".join(lines).replace("```", "` ` `")
    return f"<p><strong>{body}</strong></p>" if node.text_bold else f"<p>{body}</p>"


def _region_chunk(node: RegionNode, parent: RegionNode | None, layout: PageLayout) -> str:
    title = f"\n        title: {_text(node.title)}" if node.title else ""
    placement = ""
    if parent is not None:
        placement = f"\n            parentRegion: @{parent.id}"
    grid = _grid_lines(node.grid) if node.grid is not None else ""
    source = ""
    if node.text:
        source = f"\n        source {{\n            htmlCode: {_fence(_static_html(node))}\n        }}"
    blocks: dict[str, str] = {}
    for placed in node.body + node.hidden:
        blocks.setdefault(
            placed.block.name, placed.block.query_data_source_name or "not declared"
        )
    notes = [f"Forms {node.source}."]
    if node.note:
        notes.append(node.note)
    if blocks:
        notes.append(
            "Blocks here: "
            + "; ".join(f"{name} (source: {source})" for name, source in blocks.items())
            + ". Data binding requires schema review."
        )
    for name, records in node.tabular.items():
        notes.append(
            f"Forms shows {records} records of block {name} at once here (tabular): the "
            "first record's row is laid out; an Interactive Grid on the block's table "
            "is the next stage."
        )
    return f"""
    region {node.id} (
        name: {_text(node.name)}{title}
        type: staticContent
        layout {{
            sequence: {node.sequence}{placement}
            slot: {node.slot}{grid}
        }}
        appearance {{
            template: @/{node.template}
            templateOptions: #DEFAULT#
        }}{source}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
    )
"""


def _button_chunk(placed: Placed, region: RegionNode) -> str:
    item, block = placed.item, placed.block
    button_id = slug(f"{block.name}-{item.name}", fallback=f"button-{placed.sequence}")
    return f"""
    button {button_id} (
        buttonName: {re.sub(r'[^A-Z0-9_$#]', '_', item.name.upper())[:255]}
        label: {_text(placed.label)}
        layout {{
            sequence: {placed.sequence}
            region: @{region.id}
            slot: regionBody{_grid_lines(placed.grid)}
        }}
        appearance {{
            buttonTemplate: @/text
            templateOptions: #DEFAULT#
        }}
    )
"""


def _hidden_chunk(placed: Placed, region: RegionNode | None) -> str:
    item, block = placed.item, placed.block
    where = f"\n            region: @{region.id}\n            slot: regionBody" if region else (
        "\n            slot: body"
    )
    why = "Visible=false" if item.canvas and not item.visible else "no canvas"
    note = (
        f"Forms item {block.name}.{item.name} ({item.item_type}, {why} in Forms); "
        f"database column: {item.column_name or 'none'}; "
        f"data type: {item.data_type or 'unknown'}."
    )
    return f"""
    pageItem {placed.apex_name} (
        type: hidden
        layout {{
            sequence: {placed.sequence}{where}
        }}
        comments {{
            comments: {_fence(note)}
        }}
    )
"""


def _item_chunk(
    placed: Placed, region: RegionNode, layout: PageLayout, lov: StaticLov | None
) -> str:
    item, block = placed.item, placed.block
    kind = _item_type(item)
    # ``valueRequired`` exists on every editable item type, but APEX's own
    # compiler rejects it on ``displayOnly`` (INVALID_PROPERTY -- a Display
    # Only item has no "Value Required" in Page Designer either), and one
    # such line fails the whole import. The Forms fact is kept in the item's
    # comment instead.
    required = (
        "\n            valueRequired: true" if item.required and kind != "displayOnly" else ""
    )
    max_length = (
        f"\n            maxLength: {item.max_length}"
        if item.max_length and kind in {"textField", "textarea"}
        else ""
    )
    validation = (
        f"\n        validation {{{required}{max_length}\n        }}"
        if required or max_length
        else ""
    )
    width = layout.chars(item.width) if kind == "textField" else None
    width_line = f"\n            width: {width}" if width else ""
    # Belt-and-suspenders re-clamp of _reconcile_label's invariant: APEX
    # rejects labelColumnSpan >= columnSpan at render time only (neither
    # ``apex validate`` nor ``apex import`` catch it), so whatever upstream
    # layout path produced this Placed, never emit a span that violates it.
    label_span = placed.label_span
    if label_span and not placed.grid.flow:
        label_span = max(0, min(label_span, placed.grid.span - 1))
    template = _label_template(item, kind, side=placed.side, label_span=label_span)
    # A label left of the field takes the share of the cell the prompt took
    # on the canvas, so the field keeps its proportion to the prompt. A
    # hidden label must say 0 explicitly: Universal Theme's ``Hidden``
    # template still lays its (invisible) label out on the grid, and APEX
    # fills an unset labelColumnSpan from the page template's default -- 2
    # on every built-in page template -- before checking it against
    # columnSpan, so a hidden label on a 1- or 2-column field fails at
    # render time exactly like an oversized real one. 0 renders as
    # ``col-0`` with the field at its full columnSpan (verified on 26.1).
    if template == "hidden":
        span_line = "\n            labelColumnSpan: 0"
    elif template in {"optional", "required"} and label_span:
        span_line = f"\n            labelColumnSpan: {label_span}"
    else:
        span_line = ""
    lov_block = ""
    if lov is not None:
        null_value = "\n            displayNullValue: false" if kind == "selectList" else ""
        lov_block = f"""
        lov {{
            type: sharedComponent
            lov: @{lov.id}{null_value}
        }}"""
    notes = [
        f"Forms item {block.name}.{item.name} ({item.item_type}); "
        f"database column: {item.column_name or 'none'}; "
        f"data type: {item.data_type or 'unknown'}"
        + ("; required in Forms" if item.required else "")
        + ". "
        + _where(placed, layout)
        + "."
    ]
    if lov is not None:
        notes.append(
            f"Choices come from the shared static LOV {lov.name}; its return values "
            "were copied from the .fmb's button names/labels and need review."
        )
    if placed.note:
        notes.append(placed.note[0].upper() + placed.note[1:] + ".")
    elif template == "hidden" and not placed.caption:
        notes.append(
            "Forms shows no prompt for it, so the label template is hidden; "
            "the label text is for Page Designer only."
        )
    return f"""
    pageItem {placed.apex_name} (
        type: {kind}
        label {{
            label: {_text(placed.label)}
            alignment: {placed.align}
        }}
        layout {{
            sequence: {placed.sequence}
            region: @{region.id}
            slot: regionBody{_grid_lines(placed.grid)}{span_line}
            alignment: left
        }}
        appearance {{
            template: @/{template}
            templateOptions: #DEFAULT#{width_line}
        }}{validation}{lov_block}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
    )
"""


def _layout_chunks(layout: PageLayout) -> list[str]:
    """The page's regions, items and buttons, in the order APEXlang wants
    them: every region first (parents before children), then what each one
    holds, then the hidden items that have no region of their own."""
    chunks: list[str] = []
    lov_of = {lov.source.upper(): lov for lov in layout.lovs}

    def regions(node: RegionNode, parent: RegionNode | None) -> None:
        chunks.append(_region_chunk(node, parent, layout))
        for sub in node.subs:
            regions(sub, node)

    def contents(node: RegionNode) -> None:
        for placed in node.body:
            if "button" in placed.item.item_type.lower():
                chunks.append(_button_chunk(placed, node))
            else:
                key = f"{placed.block.name}.{placed.item.name}".upper()
                chunks.append(_item_chunk(placed, node, layout, lov_of.get(key)))
        for placed in node.hidden:
            chunks.append(_hidden_chunk(placed, node))
        for sub in node.subs:
            contents(sub)

    for root in layout.roots:
        regions(root, None)
    for root in layout.roots:
        contents(root)
    for placed in layout.hidden:
        chunks.append(_hidden_chunk(placed, None))
    return chunks


def _page_items(module: FormModule, page: int) -> tuple[list[str], dict[str, str]]:
    layout = build_layout(module, page)
    return _layout_chunks(layout), layout.names


def _lovs_text(lovs: list[StaticLov]) -> str:
    """Shared static LOVs, in the shape SQLcl's own export writes them."""
    out: list[str] = []
    for lov in lovs:
        entries: list[str] = []
        seen: set[str] = set()
        for number, (display, value) in enumerate(lov.entries, 1):
            display = " ".join(display.split()) or " ".join(value.split()) or f"Option {number}"
            entry_id = slug(display, fallback=f"entry-{number}")
            while entry_id in seen:
                entry_id = f"{entry_id}-{number}"
            seen.add(entry_id)
            entries.append(
                f"\n    entry {entry_id} (\n"
                f"        sequence: {number}\n"
                f"        display: {_text(display)}\n"
                f"        return: {_text(value or display)}\n"
                "    )\n"
            )
        out.append(
            f"\nlov {lov.id} (\n"
            f"    name: {lov.name}\n"
            "    source {\n"
            "        location: staticValues\n"
            "    }\n"
            f"{''.join(entries)}\n)\n"
        )
    return "".join(out)


def _layout_manifest(layout: PageLayout) -> dict:
    regions = []

    def walk(node: RegionNode, parent: str) -> None:
        regions.append(
            {
                "id": node.id,
                "name": node.name,
                "title": node.title,
                "template": node.template,
                "parent": parent,
                "source": node.source,
                "items": [p.apex_name for p in node.body],
                "hidden_items": [p.apex_name for p in node.hidden],
            }
        )
        for sub in node.subs:
            walk(sub, node.id)

    for root in layout.roots:
        walk(root, "")
    return {
        "regions": regions,
        "page_level_hidden_items": [p.apex_name for p in layout.hidden],
        "static_lovs": [
            {"id": lov.id, "name": lov.name, "source": lov.source, "entries": len(lov.entries)}
            for lov in layout.lovs
        ],
        "skipped": layout.skipped,
    }


def _approved_processes(store: Store, page: int) -> tuple[list[str], list[dict]]:
    chunks: list[str] = []
    manifest: list[dict] = []
    sequence = 10
    for view in store.all_views():
        if view.state != APPROVED:
            continue
        task = view.task
        code = re.sub(r":P0_([A-Za-z0-9_$#]+)", rf":P{page}_\1", view.code)
        process_id = slug(f"forms-{task['id']}", fallback=f"forms-{sequence}")
        proposal = view.proposal or {}
        note = (
            f"FormsLang approved conversion. Source: {task['kind']} {task['title']}. "
            f"Suggested target: {proposal.get('apex_target') or task.get('apex_hint') or 'review required'}. "
            "Generated as a disabled-by-default page process candidate; verify its execution point and condition in Page Designer."
        )
        chunks.append(f"""
    process {process_id} (
        name: {_text('Forms: ' + task['title'])}
        type: executeCode
        source {{
            plsqlCode:
                {_fence(code, 'plsql')}
        }}
        execution {{
            sequence: {sequence}
            point: processing
        }}
        serverSideCondition {{
            type: never
        }}
        comments {{
            comments: {_fence(note)}
        }}
    )
""")
        manifest.append({
            "task_id": task["id"],
            "source": f"{task['kind']} {task['title']}",
            "component": f"page {page} process {process_id}",
            "enabled": False,
            "reason": "execution point and condition require human confirmation",
        })
        sequence += 10
    return chunks, manifest


def _page(
    module: FormModule, store: Store, config: ApexExportConfig
) -> tuple[str, dict, PageLayout]:
    layout = build_layout(module, config.page)
    items = _layout_chunks(layout)
    processes, process_mapping = _approved_processes(store, config.page)
    title = module.title or module.name
    body = f"""page {config.page} (
    name: {_text(title)}
    alias: {slug(module.name).upper()}
    title: {_text(title)}
    appearance {{
        pageTemplate: @/standard
        templateOptions: #DEFAULT#
    }}
    navigation {{
        cursorFocus: doNotFocusCursor
    }}
    security {{
        pageAccessProtection: argumentsMustHaveChecksum
        formAutoComplete: false
    }}
{''.join(items)}{''.join(processes)}
)
"""
    mapping = {
        "items": layout.names,
        "layout": _layout_manifest(layout),
        "approved_components": process_mapping,
    }
    return body, mapping, layout


def _write_zip(zip_path: Path, project: Path) -> None:
    """Pack the project so the same files always give the same archive.

    Entries are sorted, stamped with :data:`_ZIP_EPOCH` and given one fixed
    permission mask -- nothing from the filesystem's clock or mode bits
    leaks in. Two builds of an unchanged session are byte-identical, which
    is what lets a CI job compare the ZIP it built against the one it was
    handed, and what keeps a committed ZIP from churning on every rebuild.
    """
    files = {p.relative_to(project).as_posix(): p for p in project.rglob("*") if p.is_file()}
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in sorted(files):  # by entry name, the one order every tool agrees on
            entry = zipfile.ZipInfo(name, date_time=_ZIP_EPOCH)
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o644 << 16
            archive.writestr(entry, files[name].read_bytes())


def export_apexlang(
    store: Store,
    module: FormModule,
    out_dir: Path | str,
    raw_config: dict | None = None,
) -> ApexExportResult:
    """Write an expanded APEXlang project, import ZIP, and review artifacts.

    The deployment choices are remembered on the session (see
    :func:`last_export_config`) and the checksum salt is the session's own,
    so exporting again with the same choices reproduces the same bytes.
    """
    if not _TEMPLATE.is_dir():
        raise RuntimeError(f"APEXlang 26.1 template is missing: {_TEMPLATE}")
    config = ApexExportConfig.from_dict(raw_config, module)
    out = Path(out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    project = out / config.alias
    zip_path = out / f"{config.alias}.apex.zip"
    review = out / f"{config.alias}-review"
    salt = checksum_salt(store)
    store.set_setting(SETTING_EXPORT_CONFIG, json.dumps(asdict(config)))

    with tempfile.TemporaryDirectory(prefix="formslang-apex-", dir=out) as tmp:
        staged = Path(tmp) / config.alias
        shutil.copytree(_TEMPLATE, staged)
        _write_lf(staged / "application.apx", _application(config, salt))
        _write_lf(staged / "deployments" / "default.json", _deployment(config))
        _write_lf(
            staged / ".apex" / "apexlang.json",
            json.dumps({"mmdVersion": MMD_VERSION}, indent=2) + "\n",
        )

        page_text, mapping, layout = _page(module, store, config)
        pages = staged / "pages"
        for old in pages.glob("p00001-*.apx"):
            old.unlink()
        page_file = pages / f"p{config.page:05d}-{slug(module.name)}.apx"
        _write_lf(page_file, page_text)
        if layout.lovs:
            lovs_file = staged / "shared-components" / "lovs.apx"
            _write_lf(
                lovs_file,
                lovs_file.read_text(encoding="utf-8").rstrip("\r\n")
                + "\n"
                + _lovs_text(layout.lovs),
            )

        brand = Path(__file__).resolve().parents[1] / "assets" / "brand" / "formslang-app-icon.svg"
        if brand.exists():
            static = staged / "shared-components" / "static-files"
            shutil.copy2(brand, static / "formslang-app-icon.svg")
            catalog = staged / "shared-components" / "static-files.apx"
            _write_lf(
                catalog,
                catalog.read_text(encoding="utf-8")
                + '\nfile "formslang-app-icon.svg" (\n'
                + '    mimeType: image/svg+xml\n'
                + '    charSet: utf-8\n'
                + ')\n',
            )

        if project.exists():
            shutil.rmtree(project)
        shutil.move(str(staged), str(project))

    if review.exists():
        shutil.rmtree(review)
    sql_path, json_path = store.export(review)
    manifest_path = review / "apexlang-manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "format": "APEXlang 26.1",
                "mmd_version": MMD_VERSION,
                "config": asdict(config),
                "source": store.session(),
                "stats": store.stats(),
                **mapping,
                "import": {
                    "validate": f"apex validate -input {config.alias}.apex.zip",
                    "command": f"apex import -input {config.alias}.apex.zip",
                    "database_required": True,
                },
                # The same three steps from a terminal or a CI runner --
                # what docs/ci-cd.md builds on. Password never on the
                # command line: FORMSLANG_APEX_PASSWORD, the credential
                # store, or a prompt (see cli.py).
                "cli": {
                    "export": (
                        f"formslang export {store.path.name} --app-id {config.app_id} "
                        f"--alias {config.alias} --page {config.page}"
                    ),
                    "validate": f"formslang apex validate {zip_path.name}",
                    "import": f"formslang apex import {zip_path.name}",
                },
                "reproducible": True,
            },
            ensure_ascii=False,
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )

    _write_zip(zip_path, project)

    return ApexExportResult(
        project, zip_path, sql_path, json_path, manifest_path, store.stats()[APPROVED]
    )
