"""Oracle APEX 26.1 APEXlang artifact generation.

The workbench review database is the audit trail.  This module turns the
approved part of that trail into a real APEXlang application project, using
the starter generated by SQLcl 26.1 as its immutable base.  The generated
ZIP contains only APEX application artifacts; the human-review JSON and the
flat PL/SQL file stay beside it so they cannot confuse the APEX compiler.

The page itself follows the Forms screen: :mod:`formslang.apexlayout` turns
canvas, frame and item geometry into a tree of regions on Universal Theme's
12-column grid, and this module writes that tree with the APEXlang
vocabulary that ``apex validate`` accepted on a real 26.1 database.

An export is a pure function of the session: the same approved work, the
same deployment choices, the same bytes -- ZIP included. That is what makes
the APEXlang project something a team can commit, diff and rebuild in CI
(see docs/ci-cd.md) instead of a one-off download. The only value that is
not derived from the session is the application's session-state checksum
salt, which APEX needs to be unpredictable; it is drawn once per session
and then kept (:func:`checksum_salt`).
"""

from __future__ import annotations

import html
import json
import re
import secrets
import shutil
import tempfile
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path

from . import ailayout
from .ai import Provider
from .apexlayout import (
    _DATA_TYPES,
    Grid,
    PageLayout,
    Placed,
    RegionNode,
    StaticLov,
    apex_item_type,
    bind_candidates,
    build_layout,
    button_id,
    column_name,
    database_column,
    forms_caption,
    forms_expression_default,
    item_box,
    item_default,
    layout_report,
    slug,
    sql_name,
    tabular_note,
)
from .model import Block, FormModule, Item
from .plsql import APEX_MESSAGES, FORMS_MESSAGES, SpokenMessage, spoken_messages
from .store import APPROVED, Store

MMD_VERSION = "26.1.0+3102"
_TEMPLATE = Path(__file__).with_name("templates") / "apexlang26"
_SAFE_ALIAS = re.compile(r"^[a-z][a-z0-9-]{0,79}$")

#: Session settings (``Store.setting``) this module owns.
SETTING_SALT = "apex_checksum_salt"
SETTING_EXPORT_CONFIG = "apex_export_config"

#: Every ZIP entry carries this timestamp, so the archive depends on the
#: project's bytes alone and never on the clock it was built at.
_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)


def _text(value: str, limit: int = 255) -> str:
    """Quote a one-line APEXlang string using JSON's compatible escaping."""
    clean = " ".join(str(value or "").split())[:limit]
    return json.dumps(clean, ensure_ascii=False)


def _fence(value: str, language: str = "") -> str:
    text = str(value or "").replace("\r\n", "\n").replace("\r", "\n").rstrip()
    if "```" in text:
        raise ValueError("approved code contains a triple-backtick fence")
    indented = "\n".join(f"                {line}" for line in text.split("\n"))
    return f"```{language}\n{indented}\n                ```"


def _write_lf(path: Path, text: str) -> None:
    """Write compiler-facing APEXlang files without Windows CRLF translation."""
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


@dataclass(frozen=True)
class ApexExportConfig:
    """Deployment choices. Workspace and schema may be resolved at import."""

    app_id: int = 100
    name: str = ""
    alias: str = ""
    workspace: str = ""
    schema: str = ""
    page: int = 1
    # Ask the configured AI provider to place the controls of the regions
    # the deterministic rules could not lay out cleanly (see ``ailayout``).
    # Off by default: the export stays reproducible without a provider.
    ai_layout: bool = False

    @classmethod
    def from_dict(cls, raw: dict | None, module: FormModule) -> ApexExportConfig:
        raw = raw or {}
        ai_layout = str(raw.get("ai_layout") or "").strip().lower() in {"1", "true", "on", "yes"}
        try:
            app_id = int(raw.get("app_id") or 100)
            page = int(raw.get("page") or 1)
        except (TypeError, ValueError):
            raise ValueError("application id and page must be integers") from None
        if not 1 <= app_id <= 9_999_999_999:
            raise ValueError("application id must be between 1 and 9999999999")
        if not 1 <= page <= 9_999_999_999 or page == 9999:
            raise ValueError("page must be a positive number other than 9999")

        alias = (raw.get("alias") or slug(module.name)).strip().lower()
        if not _SAFE_ALIAS.fullmatch(alias):
            raise ValueError("alias must start with a letter and use only a-z, 0-9 and hyphen")
        name = " ".join((raw.get("name") or module.title or module.name).split())[:255]
        if not name:
            raise ValueError("application name is required")
        workspace = " ".join(str(raw.get("workspace") or "").split())[:255]
        schema = " ".join(str(raw.get("schema") or "").split())[:128].upper()
        return cls(app_id, name, alias, workspace, schema, page, ai_layout)


@dataclass(frozen=True)
class ApexExportResult:
    project: Path
    zip_path: Path
    sql_path: Path
    json_path: Path
    manifest_path: Path
    approved: int
    #: One entry per block that could be a bound form, bound or not, with
    #: the reason. Same list as the manifest's ``data_binding``.
    bindings: tuple[dict, ...] = ()

    def to_dict(self) -> dict:
        return {
            "project": str(self.project),
            "zip": str(self.zip_path),
            "sql": str(self.sql_path),
            "json": str(self.json_path),
            "manifest": str(self.manifest_path),
            "approved": self.approved,
            "data_binding": [dict(entry) for entry in self.bindings],
            "format": "APEXlang 26.1",
        }


def checksum_salt(store: Store) -> str:
    """The session-state checksum salt every export of this session shares.

    APEX signs URLs with it, so it must be unpredictable: drawn once from
    the OS CSPRNG. But it is also the only byte of an export that is not
    derived from the session, so it is drawn *once* -- a re-export of the
    same approved work must produce the same ``application.apx``, or no
    diff of two exports would ever be clean.
    """
    salt = store.setting(SETTING_SALT)
    if not salt:
        salt = secrets.token_hex(32).upper()
        store.set_setting(SETTING_SALT, salt)
    return salt


def last_export_config(store: Store) -> dict:
    """The deployment choices the previous export used, or ``{}``.

    Shared by the workbench dialog (pre-filled) and ``formslang export``
    (defaults), so a command line reproduces the last click by default.
    """
    try:
        raw = json.loads(store.setting(SETTING_EXPORT_CONFIG) or "{}")
    except ValueError:
        return {}
    return raw if isinstance(raw, dict) else {}


def _application(config: ApexExportConfig, salt: str) -> str:
    return f"""app {config.alias.upper()} (
    name: {_text(config.name)}
    logo {{
        type: text
        text: &APP_TITLE.
    }}
    navigation {{
        homeUrl: {{
            page: {config.page}
        }}
        loginUrl: {{
            page: LOGIN
        }}
    }}
    navigationMenu {{
        listTemplate: @/side-navigation-menu
        templateOptions: [
            #DEFAULT#
            js-defaultCollapsed
            js-navCollapsed--hidden
            t-TreeNav--styleA
        ]
        list: @navigation-menu
    }}
    navigationBar {{
        list: @navigation-bar
        listTemplate: @/navigation-bar
        templateOptions: #DEFAULT#
    }}
    userInterface {{
        currentTheme: @universal-theme
        globalPage: 0
        addBuiltWithApexToFooter: false
    }}
    authentication {{
        scheme: @oracle-apex-accounts
    }}
    sessionStateProtection {{
        checksumSalt: {salt}
    }}
    runtime {{
        allowFeedback: true
        compatibilityMode: "26.1"
    }}
)
"""


def _deployment(config: ApexExportConfig) -> str:
    app: dict = {"id": config.app_id}
    if config.schema:
        app["databaseSession"] = {"parsingSchema": config.schema}
    data: dict = {"app": app}
    if config.workspace:
        data["workspace"] = {"name": config.workspace}
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _item_type(item: Item) -> str:
    """The native APEX item type a Forms item becomes -- see
    :func:`formslang.apexlayout.apex_item_type`. The mapping lives with the
    shared layout model so the preview and the exporter cannot disagree."""
    return apex_item_type(item)


def _template_options(options: list[str]) -> str:
    """Template options as APEXlang writes them: ``#DEFAULT#`` alone, or a
    multi-line list of the Universal Theme option classes on top of it."""
    if not options:
        return "#DEFAULT#"
    lines = "".join(f"\n                {option}" for option in ["#DEFAULT#", *options])
    return f"[{lines}\n            ]"


def _split_table(raw: str) -> tuple[str, str]:
    """(owner, table) from a query data source name: ``OWNER.TABLE`` keeps its
    owner; quotes are dropped; anything else is the table as written."""
    raw = (raw or "").strip().replace('"', "")
    owner, _, table = raw.rpartition(".")
    return sql_name(owner), sql_name(table)


def _table_ref(block: Block) -> tuple[str, str]:
    """(owner, table) for the table a block reads."""
    return _split_table(block.query_data_source_name)


def _help_text(item: Item) -> str:
    """Forms' Hint (status-line help) and Tooltip as one help text."""
    parts = [" ".join(text.split()) for text in (item.hint, item.tooltip)]
    parts = [text for text in parts if text]
    if len(parts) == 2 and parts[0].lower() == parts[1].lower():
        parts = parts[:1]
    return " ".join(parts)


def _label_template(item: Item, kind: str, *, side: str | None = None, label_span: int = 0) -> str:
    """Which Universal Theme label template reproduces the Forms caption.

    ``side`` is where Forms draws it, as :func:`formslang.apexlayout.forms_caption`
    reads it (read from the item when not given). A prompt left of the field
    -- Start, the default edge -- is a label left of the field (``optional``
    or ``required``, with ``labelColumnSpan`` giving it the room the prompt
    took); one on the top edge is a label above. Universal Theme has no
    label right of or below a field: those go above the field too, where
    they read as a caption, rather than floating inside the field where
    they would read as a placeholder. A check box's caption is the control
    itself (APEX moves the label next to the box whatever the template; the
    floating one carries the required marker). No caption at all -- nothing
    on the screen, or a ``Hidden`` prompt display style -- hides the label
    rather than inventing one. A left label whose row could not give it a
    single column (:func:`formslang.apexlayout._settle_labels` zeroes
    ``labelColumnSpan`` rather than emit one APEX rejects at render time)
    goes above the field as well.
    """
    if side is None:
        side = forms_caption(item)[1]
    if side == "none":
        return "hidden"
    required = item.required and kind not in {"displayOnly", "checkbox"}
    base = "required" if required else "optional"
    if kind == "checkbox" or side == "control":
        return f"{base}-floating"
    if side == "left" and label_span:
        return base
    return f"{base}-above"


def _bool(value: bool) -> str:
    return "true" if value else "false"


def _grid_lines(grid: Grid) -> str:
    """The layout keywords that put a box on the 12-column grid."""
    lines = [f"startNewRow: {_bool(grid.new_row)}"]
    if grid.flow:
        if not grid.new_row:
            lines.append(f"newColumn: {_bool(grid.new_column)}")
    else:
        if not grid.new_row:
            lines.append(f"newColumn: {_bool(grid.new_column)}")
        if grid.new_row or grid.new_column:
            lines.append(f"column: {grid.column}")
            lines.append(f"columnSpan: {grid.span}")
    return "".join(f"\n            {line}" for line in lines)


def _where(placed: Placed, layout: PageLayout) -> str:
    item = placed.item
    x, y, w, h = item_box(item)
    unit = layout.unit or "unit"
    caption = {
        "left": "prompt left of the field",
        "right": "prompt right of the field",
        "above": "prompt above the field",
        "below": "prompt below the field",
        "control": "caption on the control itself",
        "none": "prompt hidden" if placed.caption else "no caption shown",
    }[placed.side]
    return (
        f"Forms canvas {item.canvas}, position ({x:g}, {y:g}), size {w:g}x{h:g} "
        f"{unit.lower()}s, {caption}"
    )


def _static_html(node: RegionNode) -> str:
    """Boilerplate text as the HTML a static region shows: one paragraph,
    line breaks kept, nothing that could read as markup or close the fence."""
    lines = [
        html.escape(" ".join(line.split())) for line in node.text.splitlines() if line.strip()
    ]
    body = "<br>".join(lines).replace("```", "` ` `")
    return f"<p><strong>{body}</strong></p>" if node.text_bold else f"<p>{body}</p>"


# ---------------------------------------------------------------------------
# Confirmed data binding
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Binding:
    """A region APEX will fetch a row into and write back from.

    A binding exists only where a person left a row in the session's
    ``block_key`` table naming the column that identifies one record, and
    only when that column is one the block actually places on the page:
    APEX fetches by the value of the key's own item, so a key with no item
    fetches nothing. Everything else here is derived -- the table from the
    block, the region from the layout, the item and button names from the
    same functions that emit them.
    """

    block: str
    owner: str  # schema qualifying the table, "" when the .fmb leaves it out
    table: str
    region: str
    key_column: str
    key_item: str  # the APEX page item carrying the key
    columns: tuple[str, ...]  # the block's columns that have an item on this page
    create_button: str
    save_button: str
    confirmed_by: str
    confirmed_at: str

    @property
    def qualified(self) -> str:
        return f"{self.owner}.{self.table}" if self.owner else self.table


def confirmed_bindings(store: Store, layout: PageLayout) -> tuple[dict[str, Binding], list[dict]]:
    """The page's bound regions, and the story of every block that could be one.

    The second half of the pair is the point of the function. A block that
    *could* be bound and is not appears in the export manifest with the
    reason it was declined, so a reviewer learns a form was one confirmation
    away instead of having to work out why the page is still a set of
    unbound fields.
    """
    confirmed = store.block_keys()
    bindings: dict[str, Binding] = {}
    manifest: list[dict] = []
    for candidate in bind_candidates(layout):
        row = confirmed.get(candidate.block) or {}
        key = sql_name(row.get("key_column", ""))
        owner, table = _split_table(candidate.table)
        entry = {
            "block": candidate.block,
            "table": f"{owner}.{table}" if owner else table,
            "region": candidate.region,
            "forms_hint": candidate.suggestion,
            "confirmed_key": key,
            "confirmed_by": row.get("confirmed_by", ""),
            "confirmed_at": row.get("confirmed_at", ""),
            "bound": False,
            "reason": "",
        }
        if not key:
            entry["reason"] = (
                "no confirmed key: the region stays unbound until a reviewer names the "
                "column that identifies one row"
            )
        elif key not in candidate.columns:
            entry["reason"] = (
                f"the confirmed key {key} is not one of the columns this block places on "
                "the page, and APEX fetches the row by the value of the key's own item"
            )
        else:
            entry["bound"] = True
            bindings[candidate.region] = Binding(
                block=candidate.block,
                owner=owner,
                table=table,
                region=candidate.region,
                key_column=key,
                key_item=candidate.columns[key],
                columns=tuple(sorted(candidate.columns)),
                create_button=slug(f"{candidate.region}-create"),
                save_button=slug(f"{candidate.region}-save"),
                confirmed_by=row.get("confirmed_by", ""),
                confirmed_at=row.get("confirmed_at", ""),
            )
        manifest.append(entry)
    return bindings, manifest


def _region_chunk(
    node: RegionNode,
    parent: RegionNode | None,
    layout: PageLayout,
    binding: Binding | None = None,
) -> str:
    title = f"\n        title: {_text(node.title)}" if node.title else ""
    placement = ""
    if parent is not None:
        placement = f"\n            parentRegion: @{parent.id}"
    grid = _grid_lines(node.grid) if node.grid is not None else ""
    # Bound and boilerplate are mutually exclusive by construction: both live
    # in the ``source`` group, and a region that shows text is never offered
    # as a candidate (see apexlayout.bind_candidates). The table source goes
    # where the Interactive Grid puts its own -- right after the type, the one
    # shape ``apex import`` has already accepted on 26.1.
    kind = "staticContent"
    table_source = ""
    source = ""
    if binding is not None:
        kind = "form"
        owner_line = f"\n            tableOwner: {binding.owner}" if binding.owner else ""
        table_source = (
            "\n        source {"
            "\n            location: localDatabase"
            "\n            type: tableView"
            f"{owner_line}"
            f"\n            tableName: {binding.table}"
            "\n        }"
        )
    elif node.text:
        source = (
            f"\n        source {{\n            htmlCode: {_fence(_static_html(node))}"
            f"\n        }}"
        )
    blocks: dict[str, str] = {}
    for placed in node.body + node.hidden:
        blocks.setdefault(
            placed.block.name, placed.block.query_data_source_name or "not declared"
        )
    notes = [f"Forms {node.source}."]
    if node.note:
        notes.append(node.note)
    if blocks:
        listing = (
            "Blocks here: "
            + "; ".join(f"{name} (source: {source})" for name, source in blocks.items())
            + "."
        )
        if binding is None:
            listing += " Data binding requires schema review."
        notes.append(listing)
    if binding is not None:
        notes.append(
            f"Bound to {binding.qualified} on {binding.key_column}, confirmed by "
            f"{binding.confirmed_by or 'an unnamed reviewer'} on {binding.confirmed_at}. "
            "APEX fetches the row by that key and writes it back on submit; everything "
            "else the Forms block did on query and on commit is still behaviour to "
            "confirm."
        )
    for name, records in node.tabular.items():
        notes.append(tabular_note(node, name, records))
    return f"""
    region {node.id} (
        name: {_text(node.name)}{title}
        type: {kind}{table_source}
        layout {{
            sequence: {node.sequence}{placement}
            slot: {node.slot}{grid}
        }}
        appearance {{
            template: @/{node.template}
            templateOptions: {_template_options(node.options)}
        }}{source}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
    )
"""


def _column_chunk(
    placed: Placed, layout: PageLayout, lov: StaticLov | None, *, hidden: bool = False
) -> str:
    """One Interactive Grid column for a Forms item of a multi-record block.

    Every keyword was accepted by ``apex validate`` on 26.1 (see
    docs/layout-mapping-matrix.md): the heading is the item's prompt, the
    width/height/format mask/required/max length are the item's own, the
    source is the table column Forms binds (``ColumnName``, or the item's
    name when the .fmb leaves it out) or ``none`` for a control item. A
    hidden column carries the database items Forms keeps off the canvas --
    the primary key among them.
    """
    item, block = placed.item, placed.block
    kind = "hidden" if hidden else _item_type(item)
    name = column_name(item)
    right = item.justification.lower() in {"right", "end"}
    heading = ""
    if not hidden:
        heading = f"""
        heading {{
            heading: {_text(placed.label)}
            alignment: {"end" if right else "start"}
        }}"""
    alignment = "\n            columnAlignment: end" if right and not hidden else ""
    validation_lines: list[str] = []
    if item.required and kind not in {"displayOnly", "hidden"}:
        validation_lines.append("valueRequired: true")
    if item.max_length and kind in {"textField", "textarea"}:
        validation_lines.append(f"maxLength: {item.max_length}")
    validation = ""
    if validation_lines:
        validation = "\n        validation {" + "".join(
            f"\n            {line}" for line in validation_lines
        ) + "\n        }"
    appearance_lines: list[str] = []
    if kind in {"textField", "numberField", "datePicker", "textarea"}:
        width = layout.chars(item.width)
        if width:
            appearance_lines.append(f"width: {width}")
        if kind == "textarea" and item.height:
            rows = layout.chars(item.height, vertical=True)
            if rows and rows > 1:
                appearance_lines.append(f"height: {rows}")
        if item.format_mask and kind in {"numberField", "datePicker"}:
            appearance_lines.append(f"formatMask: {_text(item.format_mask)}")
    appearance = ""
    if appearance_lines:
        appearance = "\n        appearance {" + "".join(
            f"\n            {line}" for line in appearance_lines
        ) + "\n        }"
    settings = ""
    if kind == "checkbox" and item.checked_value and item.unchecked_value:
        settings = f"""
        settings {{
            useDefaults: false
            checkedValue: {_text(item.checked_value)}
            uncheckedValue: {_text(item.unchecked_value)}
        }}"""
    lov_block = ""
    if lov is not None and kind in {"selectList", "radioGroup"}:
        lov_block = f"""
        lov {{
            type: sharedComponent
            lov: @{lov.id}
            displayNullValue: false
        }}"""
    column = database_column(item)
    if column:
        data_type = _DATA_TYPES.get(item.data_type.lower(), "varchar2")
        primary = "\n            primaryKey: true" if item.primary_key else ""
        source = f"""
        source {{
            databaseColumn: {sql_name(column)}
            dataType: {data_type}{primary}
        }}"""
    else:
        source = """
        source {
            type: none
        }"""
    notes = [
        f"Forms item {block.name}.{item.name} ({item.item_type}); "
        f"database column: {column or 'none'}; "
        f"data type: {item.data_type or 'unknown'}"
        + ("; primary key" if item.primary_key else "")
        + ("; required in Forms" if item.required else "")
        + ("; hidden in Forms" if hidden else "")
        + "."
    ]
    if column and item.data_type.lower() not in _DATA_TYPES:
        notes.append(
            f"The Forms data type {item.data_type or 'unknown'} has no APEX column data "
            "type here; varchar2 stands in until the table is reviewed."
        )
    if not hidden:
        notes.append(_where(placed, layout) + ".")
    if _help_text(item):
        notes.append(f"Forms help: {_help_text(item)}")
    if lov is not None:
        notes.append(_lov_note(lov))
    text = f"""
    column {name} (
        type: {kind}{heading}
        layout {{
            sequence: {placed.sequence}{alignment}
        }}{validation}{appearance}{settings}{lov_block}{source}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
    )"""
    # A column sits one level inside its region.
    return chr(10).join(("    " + line) if line.strip() else line for line in text.split(chr(10)))


def _grid_chunk(
    node: RegionNode, parent: RegionNode | None, layout: PageLayout, lov_of: dict[str, StaticLov]
) -> str:
    """A multi-record block on a table as a native Interactive Grid.

    The columns come in the order Forms draws the record's items, left to
    right, each with the item's prompt as heading. The grid is read-only:
    which DML the Forms block performs (and its WHERE/ORDER BY, kept in the
    comment) is business behaviour for the developer to confirm, not for
    the converter to invent.
    """
    block = node.block
    assert block is not None
    owner, table = _table_ref(block)
    title = f"\n        title: {_text(node.title)}" if node.title else ""
    placement = ""
    if parent is not None:
        placement = f"\n            parentRegion: @{parent.id}"
    grid = _grid_lines(node.grid) if node.grid is not None else ""
    owner_line = f"\n            tableOwner: {owner}" if owner else ""
    visible = list(node.columns)
    hidden_db = [p for p in node.hidden if database_column(p.item)]
    hidden_other = [p for p in node.hidden if not database_column(p.item)]
    sequence = max([p.sequence for p in visible] + [0])
    for placed in hidden_db:
        sequence += 10
        placed.sequence = sequence
    display = "".join(
        f"""
            displayColumn (
                column: @{column_name(p.item)}
                layout {{
                    sequence: {index}
                }}
            )"""
        for index, p in enumerate(visible, 1)
    )
    columns = "".join(
        _column_chunk(p, layout, lov_of.get(f"{block.name}.{p.item.name}".upper()))
        for p in visible
    ) + "".join(_column_chunk(p, layout, None, hidden=True) for p in hidden_db)
    notes = [
        f"Forms {node.source}.",
        (
            f"Interactive Grid on {block.query_data_source_name}: one column per item of "
            f"the record, in the left-to-right order Forms draws them; Forms shows "
            f"{block.records_displayed} records at once."
        ),
        (
            "Editing is off: which DML the Forms block performs is business behaviour "
            "to confirm before enabling it."
        ),
    ]
    if block.where_clause:
        notes.append(f"Forms WHERE clause (not applied, review first): {block.where_clause}")
    if block.order_by_clause:
        notes.append(f"Forms ORDER BY (not applied, review first): {block.order_by_clause}")
    if hidden_other:
        notes.append(
            "Control items hidden in Forms stay hidden page items in this region: "
            + ", ".join(p.apex_name for p in hidden_other)
            + "."
        )
    return f"""
    region {node.id} (
        name: {_text(node.name)}{title}
        type: interactiveGrid
        source {{
            location: localDatabase{owner_line}
            tableName: {table}
        }}
        layout {{
            sequence: {node.sequence}{placement}
            slot: {node.slot}{grid}
        }}
        appearance {{
            template: @/{node.template}
            templateOptions: {_template_options(node.options)}
        }}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
        savedReport primary (
            visibility: primary
            view {{
                default: grid
            }}{display}
        ){columns}
    )
"""


def _lov_note(lov: StaticLov) -> str:
    if lov.declared:
        return (
            f"Choices come from the shared static LOV {lov.name}, with the return "
            "values the .fmb declares."
        )
    return (
        f"Choices come from the shared static LOV {lov.name}; the .fmb declares no "
        "return values, so the button names/labels stand in and need review."
    )


def _form_source(placed: Placed, binding: Binding | None, *, read_only: bool) -> str:
    """The ``source`` group that hands a page item to a form region.

    Assigning an item to a form region changes which properties apply: APEX
    then requires ``column`` and ``dataType`` (they are what it fetches and
    writes) and forbids the source ``type`` that an unbound item would carry.
    ``queryOnly`` is the safety valve. An item the user cannot type into
    submits nothing, and a column in the DML with nothing behind it is
    written as NULL -- so a read-only item is fetched and never written,
    which is what Forms did with it anyway.
    """
    if binding is None:
        return ""
    column = sql_name(database_column(placed.item))
    if not column or column not in binding.columns:
        return ""
    data_type = _DATA_TYPES.get((placed.item.data_type or "").lower(), "varchar2")
    is_key = column == binding.key_column
    lines = [
        f"formRegion: @{binding.region}",
        f"column: {column}",
        f"dataType: {data_type}",
    ]
    if read_only and not is_key:
        lines.append("queryOnly: true")
    if is_key:
        lines.append("primaryKey: true")
    body = "".join(f"\n            {line}" for line in lines)
    return f"\n        source {{{body}\n        }}"


def _form_button_chunks(node: RegionNode, binding: Binding, sequence: int) -> list[str]:
    """The buttons that submit a bound region: one to create, one to save.

    Forms commits from the menu or the SMARTBAR, neither of which survives
    the migration, so there is no button in the .fmb to carry over: without
    one the region would fetch a row and offer no way to save it. There are
    two because APEX takes the DML operation from the button's Database
    Action, not from whether the form found a row -- one button alone always
    updates, and creating a record is then impossible. Each shows when the
    other cannot apply: the key is empty on a new record and filled on one
    that was fetched. The labels are deliberately plain -- they are the first
    thing a reviewer will want to change, and changing them breaks nothing.
    """
    create_note = (
        "FormsLang added this button: the Forms module commits from the menu or the "
        "SMARTBAR, which has no APEX counterpart, so a bound region needs buttons of "
        f"its own to submit. This one inserts into {binding.qualified} and shows while "
        f"{binding.key_item} is empty, which is the page opened for a new record. APEX "
        "reads the operation from Database Action, so the insert has to have its own "
        "button. Label and placement are yours to change."
    )
    save_note = (
        "FormsLang added this button: it updates the row of "
        f"{binding.qualified} that the page fetched, and shows while {binding.key_item} "
        "has a value. Label and placement are yours to change."
    )
    return [
        f"""
    button {binding.create_button} (
        buttonName: CREATE
        label: Create
        layout {{
            sequence: {sequence}
            region: @{node.id}
            slot: regionBody
        }}
        appearance {{
            buttonTemplate: @/text
            hot: true
            templateOptions: #DEFAULT#
        }}
        behavior {{
            action: submitPage
            databaseAction: insert
            requiresConfirmation: false
        }}
        serverSideCondition {{
            type: itemIsNull
            item: {binding.key_item}
        }}
        comments {{
            comments: {_fence(create_note)}
        }}
    )
""",
        f"""
    button {binding.save_button} (
        buttonName: SAVE
        label: Save
        layout {{
            sequence: {sequence + 10}
            region: @{node.id}
            slot: regionBody
        }}
        appearance {{
            buttonTemplate: @/text
            hot: true
            templateOptions: #DEFAULT#
        }}
        behavior {{
            action: submitPage
            databaseAction: update
            requiresConfirmation: false
        }}
        serverSideCondition {{
            type: itemIsNotNull
            item: {binding.key_item}
        }}
        comments {{
            comments: {_fence(save_note)}
        }}
    )
""",
    ]


def _form_process_chunks(binding: Binding, page: int) -> list[str]:
    """Fetch, save and branch for one bound region.

    The save process sits at sequence 1000 on purpose. Approved conversions
    number from 10, so anything a reviewer enables -- a PRE-INSERT trigger
    that stamps a sequence into the key, for instance -- has already run by
    the time the row is written. The branch is not optional: a button that
    submits with no branch to follow makes APEX raise ERR-1777 at run time,
    which is a run-time failure ``apex validate`` cannot see. It has to be a
    redirect (``pageOrUrl``) and not a Show Only branch (``page``): the pages
    FormsLang writes reload on submit only for success, and APEX refuses a Show
    Only branch there -- silently, as a debug message, with the DML skipped and
    no error on screen. ``apex validate`` accepts both spellings.
    """
    fetch_note = (
        f"FormsLang generated this from Forms block {binding.block}. It fetches one row "
        f"of {binding.qualified} by {binding.key_column}, taking the value from "
        f"{binding.key_item}: with that item empty the page opens as an empty form, "
        "which is how APEX creates a row."
    )
    save_note = (
        f"FormsLang generated this from Forms block {binding.block}. It writes the "
        f"region back to {binding.qualified}, keyed by {binding.key_column}, and runs "
        "for either of the region's buttons -- the button pressed is what tells APEX "
        "whether to insert or update. Sequence 1000 keeps it behind every "
        "approved conversion, so a trigger conversion that fills a column -- a sequence "
        "into the key, a timestamp -- still runs first once you enable it."
    )
    branch_note = (
        "FormsLang generated this: a button that submits needs somewhere to go, and "
        "with no branch APEX raises ERR-1777 at run time. It redirects back to this "
        "page so the saved row is re-fetched. The redirect is deliberate -- a Show "
        "Only branch is refused at run time on a page whose Reload on Submit is Only "
        "for Success, and the submit then saves nothing without showing an error."
    )
    return [
        f"""
    process {binding.region}-form-init (
        name: {_text('Fetch ' + binding.qualified)}
        type: formInitialization
        formRegion: @{binding.region}
        execution {{
            sequence: 10
            point: beforeHeader
        }}
        comments {{
            comments: {_fence(fetch_note)}
        }}
    )
""",
        f"""
    process {binding.region}-form-dml (
        name: {_text('Save ' + binding.qualified)}
        type: formAutoRowProcessing
        formRegion: @{binding.region}
        target {{
            targetType: regionSource
        }}
        execution {{
            sequence: 1000
            point: processing
        }}
        serverSideCondition {{
            type: requestIsContainedInValue
            value: CREATE,SAVE
        }}
        comments {{
            comments: {_fence(save_note)}
        }}
    )
""",
        f"""
    branch {binding.region}-form-branch (
        execution {{
            sequence: 10
            point: afterProcessing
        }}
        behavior {{
            type: pageOrUrl
            target: {{
                page: {page}
            }}
        }}
        comments {{
            comments: {_fence(branch_note)}
        }}
    )
""",
    ]


def _button_chunk(placed: Placed, region: RegionNode) -> str:
    item = placed.item
    return f"""
    button {button_id(placed)} (
        buttonName: {re.sub(r'[^A-Z0-9_$#]', '_', item.name.upper())[:255]}
        label: {_text(placed.label)}
        layout {{
            sequence: {placed.sequence}
            region: @{region.id}
            slot: regionBody{_grid_lines(placed.grid)}
        }}
        appearance {{
            buttonTemplate: @/text
            templateOptions: #DEFAULT#
        }}
        behavior {{
            action: definedByDynamicAction
            requiresConfirmation: false
        }}
    )
"""


def _hidden_chunk(
    placed: Placed, region: RegionNode | None, binding: Binding | None = None
) -> str:
    item, block = placed.item, placed.block
    where = f"\n            region: @{region.id}\n            slot: regionBody" if region else (
        "\n            slot: body"
    )
    why = "Visible=false" if item.canvas and not item.visible else "no canvas"
    note = (
        f"Forms item {block.name}.{item.name} ({item.item_type}, {why} in Forms); "
        f"database column: {database_column(item) or 'none'}; "
        f"data type: {item.data_type or 'unknown'}"
        + ("; primary key" if item.primary_key else "")
        + "."
    )
    source = _form_source(placed, binding, read_only=False)
    return f"""
    pageItem {placed.apex_name} (
        type: hidden
        layout {{
            sequence: {placed.sequence}{where}
        }}{source}
        comments {{
            comments: {_fence(note)}
        }}
    )
"""


def _item_chunk(
    placed: Placed,
    region: RegionNode,
    layout: PageLayout,
    lov: StaticLov | None,
    binding: Binding | None = None,
) -> str:
    item, block = placed.item, placed.block
    kind = _item_type(item)
    # ``valueRequired`` exists on every editable item type, but APEX's own
    # compiler rejects it on ``displayOnly`` (INVALID_PROPERTY -- a Display
    # Only item has no "Value Required" in Page Designer either), and one
    # such line fails the whole import. The Forms fact is kept in the item's
    # comment instead.
    # A required check box in APEX must be *checked*; in Forms "required"
    # only means the item has a value, which a check box always has. The
    # fact stays in the comment, the item stays optional.
    required = (
        "\n            valueRequired: true"
        if item.required and kind not in {"displayOnly", "checkbox"}
        else ""
    )
    max_length = (
        f"\n            maxLength: {item.max_length}"
        if item.max_length and kind in {"textField", "textarea"}
        else ""
    )
    validation = (
        f"\n        validation {{{required}{max_length}\n        }}"
        if required or max_length
        else ""
    )
    appearance_lines: list[str] = []
    if kind in {"textField", "numberField", "datePicker", "textarea"}:
        width = layout.chars(item.width)
        if width:
            appearance_lines.append(f"width: {width}")
        if kind == "textarea" and item.height:
            rows = layout.chars(item.height, vertical=True)
            if rows and rows > 1:
                appearance_lines.append(f"height: {rows}")
        if item.format_mask and kind in {"numberField", "datePicker"}:
            appearance_lines.append(f"formatMask: {_text(item.format_mask)}")
    width_line = "".join(f"\n            {line}" for line in appearance_lines)
    # Belt-and-suspenders re-clamp of _settle_labels' invariant: APEX
    # rejects labelColumnSpan >= columnSpan at render time only (neither
    # ``apex validate`` nor ``apex import`` catch it), so whatever upstream
    # layout path produced this Placed, never emit a span that violates it.
    label_span = placed.label_span
    if label_span and not placed.grid.flow:
        label_span = max(0, min(label_span, placed.grid.span - 1))
    template = _label_template(item, kind, side=placed.side, label_span=label_span)
    # A label left of the field takes the share of the cell the prompt took
    # on the canvas, so the field keeps its proportion to the prompt. A
    # hidden label must say 0 explicitly: Universal Theme's ``Hidden``
    # template still lays its (invisible) label out on the grid, and APEX
    # fills an unset labelColumnSpan from the page template's default -- 2
    # on every built-in page template -- before checking it against
    # columnSpan, so a hidden label on a 1- or 2-column field fails at
    # render time exactly like an oversized real one. 0 renders as
    # ``col-0`` with the field at its full columnSpan (verified on 26.1).
    if template == "hidden":
        span_line = "\n            labelColumnSpan: 0"
    elif template in {"optional", "required"} and label_span:
        span_line = f"\n            labelColumnSpan: {label_span}"
    else:
        span_line = ""
    lov_block = ""
    if lov is not None:
        lov_block = f"""
        lov {{
            type: sharedComponent
            lov: @{lov.id}
            displayNullValue: false
        }}"""
    # Native settings the Forms item declares -- each keyword verified by
    # ``apex validate`` on 26.1 for the item type it goes with.
    settings_lines: list[str] = []
    if kind == "radioGroup" and placed.radio_columns > 1:
        settings_lines.append(f"noOfCols: {placed.radio_columns}")
    if kind == "checkbox" and item.checked_value and item.unchecked_value:
        settings_lines.append("useDefaults: false")
        settings_lines.append(f"checkedValue: {_text(item.checked_value)}")
        settings_lines.append(f"uncheckedValue: {_text(item.unchecked_value)}")
    if kind == "textField" and item.case_restriction.lower() in {"upper", "lower"}:
        settings_lines.append(f"textCase: {item.case_restriction.lower()}")
    if kind == "numberField" and item.justification.lower() in {"right", "end"}:
        settings_lines.append("numberAlignment: end")
    settings = ""
    if settings_lines:
        settings = "\n        settings {" + "".join(
            f"\n            {line}" for line in settings_lines
        ) + "\n        }"
    # A literal InitializeValue is the item's static default (verified on
    # 26.1: ``default { type: static staticValue }`` fills the field on
    # render, a display-only item included); a Forms expression is not.
    default_block = ""
    default_value, _, default_note = item_default(item)
    if default_value:
        default_block = f"""
        default {{
            type: static
            staticValue: {_text(default_value)}
        }}"""
    help_block = ""
    if _help_text(item):
        help_block = f"""
        help {{
            helpText: {_text(_help_text(item), 4000)}
        }}"""
    # Enabled=false in Forms greys the field out but keeps its value in the
    # record; APEX's read-only item does the same (a disabled item would
    # drop out of the submit).
    read_only = ""
    if not item.enabled and kind != "displayOnly":
        read_only = """
        readOnly {
            type: always
        }"""
    notes = [
        f"Forms item {block.name}.{item.name} ({item.item_type}); "
        f"database column: {database_column(item) or 'none'}; "
        f"data type: {item.data_type or 'unknown'}"
        + ("; primary key" if item.primary_key else "")
        + ("; required in Forms" if item.required else "")
        + ("; disabled in Forms (read only here)" if not item.enabled else "")
        + ". "
        + _where(placed, layout)
        + "."
    ]
    if item.format_mask and kind not in {"numberField", "datePicker"}:
        notes.append(f"Forms format mask (no native property on a {kind}): {item.format_mask}.")
    if forms_expression_default(item):
        notes.append(
            f"Forms initial value {forms_expression_default(item)} is an expression, not a "
            "literal: set a computation or a default of another type."
        )
    if default_note:
        notes.append(f"Forms {default_note}.")
    if item.required and kind == "checkbox":
        notes.append(
            "Required in Forms only means the item has a value; a required APEX check box "
            "must be checked, so it is left optional here."
        )
    if lov is not None:
        notes.append(_lov_note(lov))
    source = _form_source(
        placed, binding, read_only=kind == "displayOnly" or not item.enabled
    )
    if placed.note:
        notes.append(placed.note[0].upper() + placed.note[1:] + ".")
    elif template == "hidden" and not placed.caption:
        notes.append(
            "Forms shows no prompt for it, so the label template is hidden; "
            "the label text is for Page Designer only."
        )
    return f"""
    pageItem {placed.apex_name} (
        type: {kind}
        label {{
            label: {_text(placed.label)}
            alignment: {placed.align}
        }}
        layout {{
            sequence: {placed.sequence}
            region: @{region.id}
            slot: regionBody{_grid_lines(placed.grid)}{span_line}
            alignment: left
        }}
        appearance {{
            template: @/{template}
            templateOptions: #DEFAULT#{width_line}
        }}{validation}{settings}{lov_block}{default_block}{help_block}{read_only}{source}
        comments {{
            comments: {_fence(" ".join(notes))}
        }}
    )
"""


def _layout_chunks(
    layout: PageLayout, bindings: dict[str, Binding] | None = None
) -> list[str]:
    """The page's regions, items and buttons, in the order APEXlang wants
    them: every region first (parents before children), then what each one
    holds, then the hidden items that have no region of their own.

    ``bindings`` maps a region id to the table a reviewer confirmed for it.
    With none -- the default, and every export before a confirmation exists
    -- the output is what it has always been, byte for byte.
    """
    chunks: list[str] = []
    bindings = bindings or {}
    lov_of = {lov.source.upper(): lov for lov in layout.lovs}

    def regions(node: RegionNode, parent: RegionNode | None) -> None:
        if node.kind == "grid":
            chunks.append(_grid_chunk(node, parent, layout, lov_of))
        else:
            chunks.append(_region_chunk(node, parent, layout, bindings.get(node.id)))
        for sub in node.subs:
            regions(sub, node)

    def contents(node: RegionNode) -> None:
        binding = bindings.get(node.id)
        for placed in node.body:
            if "button" in placed.item.item_type.lower():
                chunks.append(_button_chunk(placed, node))
            else:
                key = f"{placed.block.name}.{placed.item.name}".upper()
                chunks.append(_item_chunk(placed, node, layout, lov_of.get(key), binding))
        for placed in node.hidden:
            # A grid's database items became hidden columns of the grid;
            # only its control items stay hidden page items.
            if node.kind == "grid" and database_column(placed.item):
                continue
            chunks.append(_hidden_chunk(placed, node, binding))
        if binding is not None:
            # After the region's own contents, so the button lands under the
            # last field rather than between two of them.
            last = max((p.sequence for p in node.body), default=0)
            chunks.extend(_form_button_chunks(node, binding, last + 10))
        for sub in node.subs:
            contents(sub)

    for root in layout.roots:
        regions(root, None)
    for root in layout.roots:
        contents(root)
    for placed in layout.hidden:
        chunks.append(_hidden_chunk(placed, None))
    return chunks


def _page_items(module: FormModule, page: int) -> tuple[list[str], dict[str, str]]:
    layout = build_layout(module, page)
    return _layout_chunks(layout), layout.names


def _lovs_text(lovs: list[StaticLov]) -> str:
    """Shared static LOVs, in the shape SQLcl's own export writes them."""
    out: list[str] = []
    for lov in lovs:
        entries: list[str] = []
        seen: set[str] = set()
        for number, (display, value) in enumerate(lov.entries, 1):
            display = " ".join(display.split()) or " ".join(value.split()) or f"Option {number}"
            entry_id = slug(display, fallback=f"entry-{number}")
            while entry_id in seen:
                entry_id = f"{entry_id}-{number}"
            seen.add(entry_id)
            entries.append(
                f"\n    entry {entry_id} (\n"
                f"        sequence: {number}\n"
                f"        display: {_text(display)}\n"
                f"        return: {_text(value or display)}\n"
                "    )\n"
            )
        out.append(
            f"\nlov {lov.id} (\n"
            f"    name: {lov.name}\n"
            "    source {\n"
            "        location: staticValues\n"
            "    }\n"
            f"{''.join(entries)}\n)\n"
        )
    return "".join(out)


def _layout_manifest(layout: PageLayout) -> dict:
    regions = []

    def walk(node: RegionNode, parent: str) -> None:
        regions.append(
            {
                "id": node.id,
                "name": node.name,
                "title": node.title,
                "template": node.template,
                "parent": parent,
                "source": node.source,
                "kind": node.kind,
                "template_options": list(node.options),
                "items": [p.apex_name for p in node.body],
                "columns": [column_name(p.item) for p in node.columns],
                "hidden_items": [p.apex_name for p in node.hidden],
                "derived": node.derived,
            }
        )
        for sub in node.subs:
            walk(sub, node.id)

    for root in layout.roots:
        walk(root, "")
    return {
        "regions": regions,
        "page_level_hidden_items": [p.apex_name for p in layout.hidden],
        "static_lovs": [
            {
                "id": lov.id,
                "name": lov.name,
                "source": lov.source,
                "entries": len(lov.entries),
                "return_values_declared": lov.declared,
            }
            for lov in layout.lovs
        ],
        "skipped": layout.skipped,
        "ai_layout": layout.ai,
        "mapping_report": layout_report(layout),
    }


#: The two Forms triggers the rule engine already calls validations (both
#: AUTO in rules.py). Every other approved conversion stays a page process;
#: these become the APEX component the rule engine promised.
_VALIDATION_TRIGGERS = {
    "WHEN-VALIDATE-ITEM": "item",
    "WHEN-VALIDATE-RECORD": "record",
}

#: A page item declaration inside an emitted layout chunk -- four spaces,
#: the indentation _item_chunk and _hidden_chunk write.
_PAGE_ITEM_DECL = re.compile(r"^    pageItem ([A-Za-z0-9_$#]+) \(", re.MULTILINE)


def _emitted_page_items(chunks: list[str]) -> set[str]:
    """Which page items this page actually declares.

    A validation may only point at an item that exists. A Forms item that
    became an Interactive Grid column, or that no region took, never gets a
    ``pageItem`` of its own, and ``associatedItem: @P1_X`` for one fails the
    import with COMPONENT_NOT_FOUND. Reading the emitted chunks back is the
    one source that cannot drift from what :func:`_layout_chunks` decided.
    """
    return {m.group(1) for chunk in chunks for m in _PAGE_ITEM_DECL.finditer(chunk)}


def _validation_kind(task: dict) -> str:
    """``"item"``, ``"record"``, or ``""`` when the unit is not a validation."""
    if task.get("kind") != "trigger":
        return ""
    return _VALIDATION_TRIGGERS.get(str(task.get("name") or "").upper(), "")


#: Longer than this and :func:`_text` would cut the sentence in half. Half a
#: sentence in front of a user is worse than an honest placeholder.
_MESSAGE_LIMIT = 255


@dataclass(frozen=True)
class _ErrorMessage:
    """The wording a validation shows, and where it was read from."""

    text: str
    #: The source it came from, or "" when ``text`` is the placeholder.
    origin: str
    #: What to tell the reviewer, in the component comments.
    notes: tuple[str, ...] = ()


def _undecided(origin: str, spoken: list[SpokenMessage], readable: list[str]) -> str:
    """Why a source that did speak still did not get to set the message."""
    if len(readable) > 1:
        candidates = "; ".join(f'"{text}"' for text in readable)
        return (
            f"The {origin} shows more than one message and nothing here can tell which "
            f"one belongs to this rule: {candidates}. Pick one."
        )
    if readable:
        return (
            f"The {origin} message is longer than {_MESSAGE_LIMIT} characters, which is "
            "all an APEX error message holds. Shorten it and paste it here."
        )
    built = "; ".join(message.expression for message in spoken if message.expression)
    return (
        f"The {origin} builds its message at run time ({built}), so there is no sentence "
        "in the source to copy."
    )


def _error_message(task: dict, code: str) -> _ErrorMessage:
    """The sentence the end user should read when this rule rejects a value.

    APEX prints the validation's own ``errorMessage``. The error the code
    raises inside ``plsqlCodeRaisingError`` never reaches the page, so the
    wording has to be lifted out of the code and put in the message -- or the
    user reads a placeholder while the real sentence sits three lines below
    it, which is what this converter shipped before.

    Sources are read best first: what the approved code says wins, because
    that is the code that will run; the Forms trigger is the fallback,
    because that is the sentence the form has been showing all along. The
    first source that says exactly one readable thing decides. A source that
    says two different things, or builds its sentence at run time, does not
    get to guess: it is reported in the notes and the search moves on.
    """
    sources = (
        ("approved code", code, APEX_MESSAGES),
        ("Forms trigger", str(task.get("source") or ""), FORMS_MESSAGES),
    )
    notes: list[str] = []
    for origin, body, builtins in sources:
        spoken = spoken_messages(body, builtins)
        if not spoken:
            continue
        readable: list[str] = []
        for message in spoken:
            if message.text and message.text not in readable:
                readable.append(message.text)
        if len(readable) == 1 and len(readable[0]) <= _MESSAGE_LIMIT:
            return _ErrorMessage(readable[0], origin, tuple(notes))
        notes.append(_undecided(origin, spoken, readable))
    placeholder = (
        f"Forms validation {task['title']} failed. Replace this text with the message "
        "your users should see."
    )
    return _ErrorMessage(placeholder, "", tuple(notes))


def _validation_chunk(
    task: dict,
    code: str,
    page: int,
    sequence: int,
    kind: str,
    component_id: str,
    names: dict[str, str],
    emitted: set[str],
    target: str,
) -> tuple[str, dict]:
    """An approved WHEN-VALIDATE trigger as a real APEX page validation.

    The type is ``plsqlError`` -- "passes if the code runs without raising an
    error" -- because that is what the Forms trigger did and what the
    approved code still is: a PL/SQL block that raises, or calls
    ``apex_error.add_error``, when the value is wrong. ``functionBody``
    would demand a RETURN on every path, which a converted trigger body does
    not have; it would import cleanly and then fail at runtime, which is
    worse than not converting it at all.

    Unlike a process, this component is born enabled. An approved rule that
    imports switched off enforces nothing, and a reviewer already said the
    code is right. The wording comes from :func:`_error_message`, which reads
    it out of the approved code or, failing that, out of the Forms trigger;
    only when neither says one readable thing does the placeholder survive.
    """
    owner = str(task.get("owner") or "")
    mapped = names.get(owner.upper(), "") if kind == "item" and "." in owner else ""
    apex_item = mapped if mapped in emitted else ""
    chosen = _error_message(task, code)
    notes = [
        "FormsLang approved conversion.",
        f"Source: {task['kind']} {task['title']}.",
        f"Suggested target: {target}.",
        (
            "Page validation of type PL/SQL Error: it passes when the approved code runs "
            "without raising, which is how the Forms trigger rejected a value."
        ),
    ]
    if chosen.origin:
        notes.append(
            "Enabled, because a reviewer approved the rule. The error message is the "
            f"one the {chosen.origin} already showed: APEX prints this text and never "
            "the error the code raises, so read it once before you ship it."
        )
    else:
        notes.append(
            "Enabled, because a reviewer approved the rule; the error message is a "
            "placeholder -- replace it with the wording your users should see."
        )
    notes.extend(chosen.notes)
    if kind == "record":
        notes.append(
            f"Forms validated the whole record of block {owner or 'unknown'}, not one "
            "field, so the error shows in the notification."
        )
    elif not apex_item:
        if "." not in owner:
            why = f"The trigger belongs to {owner or 'the form'}, not to one item"
        elif not mapped:
            why = f"Forms item {owner} has no page item on this page"
        else:
            why = (
                f"Forms item {owner} is not a page item here: {mapped} became an "
                "Interactive Grid column, or no region took it"
            )
        notes.append(why + ", so the error shows in the notification, not next to a field.")
    location = "inlineWithFieldAndInNotification" if apex_item else "inlineInNotification"
    associated = f"\n            associatedItem: @{apex_item}" if apex_item else ""
    chunk = f"""
    validation {component_id} (
        name: {_text('Forms: ' + task['title'])}
        validation {{
            type: plsqlError
            plsqlCodeRaisingError:
                {_fence(code, 'plsql')}
        }}
        error {{
            errorMessage: {_text(chosen.text)}
            displayLocation: {location}{associated}
        }}
        execution {{
            sequence: {sequence}
        }}
        comments {{
            comments: {_fence(' '.join(notes))}
        }}
    )
"""
    entry = {
        "task_id": task["id"],
        "source": f"{task['kind']} {task['title']}",
        "component": f"page {page} validation {component_id}",
        "kind": "validation",
        "enabled": True,
        "reason": (
            f"approved rule, enforced on submit; message read from the {chosen.origin}"
            if chosen.origin
            else "approved rule, enforced on submit; the error message is a placeholder"
        ),
        "associated_item": apex_item,
        "message_source": chosen.origin or "placeholder",
    }
    return chunk, entry


def _process_chunk(
    task: dict, code: str, page: int, sequence: int, component_id: str, target: str
) -> tuple[str, dict]:
    """An approved conversion with no APEX component of its own, parked as a
    disabled page process for a human to place."""
    note = (
        f"FormsLang approved conversion. Source: {task['kind']} {task['title']}. "
        f"Suggested target: {target}. "
        "Generated as a disabled-by-default page process candidate; verify its execution "
        "point and condition in Page Designer."
    )
    chunk = f"""
    process {component_id} (
        name: {_text('Forms: ' + task['title'])}
        type: executeCode
        source {{
            plsqlCode:
                {_fence(code, 'plsql')}
        }}
        execution {{
            sequence: {sequence}
            point: processing
        }}
        serverSideCondition {{
            type: never
        }}
        comments {{
            comments: {_fence(note)}
        }}
    )
"""
    entry = {
        "task_id": task["id"],
        "source": f"{task['kind']} {task['title']}",
        "component": f"page {page} process {component_id}",
        "kind": "process",
        "enabled": False,
        "reason": "execution point and condition require human confirmation",
    }
    return chunk, entry


def _approved_components(
    store: Store, page: int, names: dict[str, str], emitted: set[str]
) -> tuple[list[str], list[dict]]:
    """Every approved conversion, as the component it belongs in.

    Validations are emitted before processes -- the order Page Designer
    lists them in -- and each family numbers its own execution sequence from
    10, so enabling or removing one never renumbers the other. Two exports
    of one session give the same text: the views come back in task order and
    nothing here reads a clock.
    """
    validations: list[str] = []
    processes: list[str] = []
    validation_manifest: list[dict] = []
    process_manifest: list[dict] = []
    validation_sequence = process_sequence = 10
    for view in store.all_views():
        if view.state != APPROVED:
            continue
        task = view.task
        code = re.sub(r":P0_([A-Za-z0-9_$#]+)", rf":P{page}_\1", view.code)
        proposal = view.proposal or {}
        target = proposal.get("apex_target") or task.get("apex_hint") or "review required"
        kind = _validation_kind(task)
        if kind:
            component_id = slug(
                f"forms-{task['id']}", fallback=f"forms-validation-{validation_sequence}"
            )
            chunk, entry = _validation_chunk(
                task, code, page, validation_sequence, kind, component_id,
                names, emitted, target,
            )
            validations.append(chunk)
            validation_manifest.append(entry)
            validation_sequence += 10
        else:
            component_id = slug(
                f"forms-{task['id']}", fallback=f"forms-process-{process_sequence}"
            )
            chunk, entry = _process_chunk(task, code, page, process_sequence, component_id, target)
            processes.append(chunk)
            process_manifest.append(entry)
            process_sequence += 10
    return validations + processes, validation_manifest + process_manifest


def _page(
    module: FormModule, store: Store, config: ApexExportConfig, provider: Provider | None = None
) -> tuple[str, dict, PageLayout]:
    layout = build_layout(module, config.page)
    if config.ai_layout:
        ailayout.assist(layout, provider, store, config.page)
    bindings, binding_manifest = confirmed_bindings(store, layout)
    items = _layout_chunks(layout, bindings)
    components, component_mapping = _approved_components(
        store, config.page, layout.names, _emitted_page_items(items)
    )
    for binding in bindings.values():
        components.extend(_form_process_chunks(binding, config.page))
    title = module.title or module.name
    body = f"""page {config.page} (
    name: {_text(title)}
    alias: {slug(module.name).upper()}
    title: {_text(title)}
    appearance {{
        pageTemplate: @/standard
        templateOptions: #DEFAULT#
    }}
    navigation {{
        cursorFocus: doNotFocusCursor
    }}
    security {{
        pageAccessProtection: argumentsMustHaveChecksum
        formAutoComplete: false
    }}
{''.join(items)}{''.join(components)}
)
"""
    mapping = {
        "items": layout.names,
        "layout": _layout_manifest(layout),
        "approved_components": component_mapping,
        "data_binding": binding_manifest,
    }
    return body, mapping, layout


def _write_zip(zip_path: Path, project: Path) -> None:
    """Pack the project so the same files always give the same archive.

    Entries are sorted, stamped with :data:`_ZIP_EPOCH` and given one fixed
    permission mask -- nothing from the filesystem's clock or mode bits
    leaks in. Two builds of an unchanged session are byte-identical, which
    is what lets a CI job compare the ZIP it built against the one it was
    handed, and what keeps a committed ZIP from churning on every rebuild.
    """
    files = {p.relative_to(project).as_posix(): p for p in project.rglob("*") if p.is_file()}
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name in sorted(files):  # by entry name, the one order every tool agrees on
            entry = zipfile.ZipInfo(name, date_time=_ZIP_EPOCH)
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o644 << 16
            archive.writestr(entry, files[name].read_bytes())


def export_apexlang(
    store: Store,
    module: FormModule,
    out_dir: Path | str,
    raw_config: dict | None = None,
    provider: Provider | None = None,
) -> ApexExportResult:
    """Write an expanded APEXlang project, import ZIP, and review artifacts.

    The deployment choices are remembered on the session (see
    :func:`last_export_config`) and the checksum salt is the session's own,
    so exporting again with the same choices reproduces the same bytes.
    With ``ai_layout`` on, ``provider`` (the session's, or the environment's
    when None) is asked about the regions the rules could not lay out
    cleanly; its plan is cached on the session, so that export is
    reproducible too (see :mod:`formslang.ailayout`).
    """
    if not _TEMPLATE.is_dir():
        raise RuntimeError(f"APEXlang 26.1 template is missing: {_TEMPLATE}")
    config = ApexExportConfig.from_dict(raw_config, module)
    out = Path(out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    project = out / config.alias
    zip_path = out / f"{config.alias}.apex.zip"
    review = out / f"{config.alias}-review"
    salt = checksum_salt(store)
    store.set_setting(SETTING_EXPORT_CONFIG, json.dumps(asdict(config)))

    with tempfile.TemporaryDirectory(prefix="formslang-apex-", dir=out) as tmp:
        staged = Path(tmp) / config.alias
        shutil.copytree(_TEMPLATE, staged)
        _write_lf(staged / "application.apx", _application(config, salt))
        _write_lf(staged / "deployments" / "default.json", _deployment(config))
        _write_lf(
            staged / ".apex" / "apexlang.json",
            json.dumps({"mmdVersion": MMD_VERSION}, indent=2) + "\n",
        )

        page_text, mapping, layout = _page(module, store, config, provider)
        pages = staged / "pages"
        for old in pages.glob("p00001-*.apx"):
            old.unlink()
        page_file = pages / f"p{config.page:05d}-{slug(module.name)}.apx"
        _write_lf(page_file, page_text)
        if layout.lovs:
            lovs_file = staged / "shared-components" / "lovs.apx"
            _write_lf(
                lovs_file,
                lovs_file.read_text(encoding="utf-8").rstrip("\r\n")
                + "\n"
                + _lovs_text(layout.lovs),
            )

        brand = Path(__file__).resolve().parents[1] / "assets" / "brand" / "formslang-app-icon.svg"
        if brand.exists():
            static = staged / "shared-components" / "static-files"
            shutil.copy2(brand, static / "formslang-app-icon.svg")
            catalog = staged / "shared-components" / "static-files.apx"
            _write_lf(
                catalog,
                catalog.read_text(encoding="utf-8")
                + '\nfile "formslang-app-icon.svg" (\n'
                + '    mimeType: image/svg+xml\n'
                + '    charSet: utf-8\n'
                + ')\n',
            )

        if project.exists():
            shutil.rmtree(project)
        shutil.move(str(staged), str(project))

    if review.exists():
        shutil.rmtree(review)
    sql_path, json_path = store.export(review)
    manifest_path = review / "apexlang-manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "format": "APEXlang 26.1",
                "mmd_version": MMD_VERSION,
                "config": asdict(config),
                "source": store.session(),
                "stats": store.stats(),
                **mapping,
                "import": {
                    "validate": f"apex validate -input {config.alias}.apex.zip",
                    "command": f"apex import -input {config.alias}.apex.zip",
                    "database_required": True,
                },
                # The same three steps from a terminal or a CI runner --
                # what docs/ci-cd.md builds on. Password never on the
                # command line: FORMSLANG_APEX_PASSWORD, the credential
                # store, or a prompt (see cli.py).
                "cli": {
                    "export": (
                        f"formslang export {store.path.name} --app-id {config.app_id} "
                        f"--alias {config.alias} --page {config.page}"
                        + (" --ai-layout" if config.ai_layout else "")
                    ),
                    "validate": f"formslang apex validate {zip_path.name}",
                    "import": f"formslang apex import {zip_path.name}",
                },
                "reproducible": True,
            },
            ensure_ascii=False,
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )

    _write_zip(zip_path, project)

    return ApexExportResult(
        project,
        zip_path,
        sql_path,
        json_path,
        manifest_path,
        store.stats()[APPROVED],
        tuple(mapping.get("data_binding") or ()),
    )
