"""Oracle APEX 26.1 APEXlang artifact generation.

The workbench review database is the audit trail.  This module turns the
approved part of that trail into a real APEXlang application project, using
the starter generated by SQLcl 26.1 as its immutable base.  The generated
ZIP contains only APEX application artifacts; the human-review JSON and the
flat PL/SQL file stay beside it so they cannot confuse the APEX compiler.
"""

from __future__ import annotations

import json
import re
import secrets
import shutil
import tempfile
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path

from .model import FormModule, Item
from .store import APPROVED, Store

MMD_VERSION = "26.1.0+3102"
_TEMPLATE = Path(__file__).with_name("templates") / "apexlang26"
_SAFE_ALIAS = re.compile(r"^[a-z][a-z0-9-]{0,79}$")


def slug(value: str, *, fallback: str = "formslang-app") -> str:
    """A filesystem-safe APEX alias and human-readable component id."""
    text = re.sub(r"[^a-z0-9]+", "-", (value or "").strip().lower()).strip("-")
    if not text or not text[0].isalpha():
        text = f"app-{text}" if text else fallback
    return text[:80].rstrip("-")


def _text(value: str, limit: int = 255) -> str:
    """Quote a one-line APEXlang string using JSON's compatible escaping."""
    clean = " ".join(str(value or "").split())[:limit]
    return json.dumps(clean, ensure_ascii=False)


def _fence(value: str, language: str = "") -> str:
    text = str(value or "").replace("\r\n", "\n").replace("\r", "\n").rstrip()
    if "```" in text:
        raise ValueError("approved code contains a triple-backtick fence")
    indented = "\n".join(f"                {line}" for line in text.split("\n"))
    return f"```{language}\n{indented}\n                ```"


def _write_lf(path: Path, text: str) -> None:
    """Write compiler-facing APEXlang files without Windows CRLF translation."""
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


@dataclass(frozen=True)
class ApexExportConfig:
    """Deployment choices. Workspace and schema may be resolved at import."""

    app_id: int = 100
    name: str = ""
    alias: str = ""
    workspace: str = ""
    schema: str = ""
    page: int = 1

    @classmethod
    def from_dict(cls, raw: dict | None, module: FormModule) -> ApexExportConfig:
        raw = raw or {}
        try:
            app_id = int(raw.get("app_id") or 100)
            page = int(raw.get("page") or 1)
        except (TypeError, ValueError):
            raise ValueError("application id and page must be integers") from None
        if not 1 <= app_id <= 9_999_999_999:
            raise ValueError("application id must be between 1 and 9999999999")
        if not 1 <= page <= 9_999_999_999 or page == 9999:
            raise ValueError("page must be a positive number other than 9999")

        alias = (raw.get("alias") or slug(module.name)).strip().lower()
        if not _SAFE_ALIAS.fullmatch(alias):
            raise ValueError("alias must start with a letter and use only a-z, 0-9 and hyphen")
        name = " ".join((raw.get("name") or module.title or module.name).split())[:255]
        if not name:
            raise ValueError("application name is required")
        workspace = " ".join(str(raw.get("workspace") or "").split())[:255]
        schema = " ".join(str(raw.get("schema") or "").split())[:128].upper()
        return cls(app_id, name, alias, workspace, schema, page)


@dataclass(frozen=True)
class ApexExportResult:
    project: Path
    zip_path: Path
    sql_path: Path
    json_path: Path
    manifest_path: Path
    approved: int

    def to_dict(self) -> dict:
        return {
            "project": str(self.project),
            "zip": str(self.zip_path),
            "sql": str(self.sql_path),
            "json": str(self.json_path),
            "manifest": str(self.manifest_path),
            "approved": self.approved,
            "format": "APEXlang 26.1",
        }


def _application(config: ApexExportConfig) -> str:
    salt = secrets.token_hex(32).upper()
    return f"""app {config.alias.upper()} (
    name: {_text(config.name)}
    logo {{
        type: text
        text: &APP_TITLE.
    }}
    navigation {{
        homeUrl: {{
            page: {config.page}
        }}
        loginUrl: {{
            page: LOGIN
        }}
    }}
    navigationMenu {{
        listTemplate: @/side-navigation-menu
        templateOptions: [
            #DEFAULT#
            js-defaultCollapsed
            js-navCollapsed--hidden
            t-TreeNav--styleA
        ]
        list: @navigation-menu
    }}
    navigationBar {{
        list: @navigation-bar
        listTemplate: @/navigation-bar
        templateOptions: #DEFAULT#
    }}
    userInterface {{
        currentTheme: @universal-theme
        globalPage: 0
        addBuiltWithApexToFooter: false
    }}
    authentication {{
        scheme: @oracle-apex-accounts
    }}
    sessionStateProtection {{
        checksumSalt: {salt}
    }}
    runtime {{
        allowFeedback: true
        compatibilityMode: "26.1"
    }}
)
"""


def _deployment(config: ApexExportConfig) -> str:
    app: dict = {"id": config.app_id}
    if config.schema:
        app["databaseSession"] = {"parsingSchema": config.schema}
    data: dict = {"app": app}
    if config.workspace:
        data["workspace"] = {"name": config.workspace}
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def _item_type(item: Item) -> str:
    kind = item.item_type.lower()
    if "display" in kind:
        return "displayOnly"
    if "editor" in kind or "area" in kind:
        return "textArea"
    return "textField"


def _page_items(module: FormModule, page: int) -> tuple[list[str], dict[str, str]]:
    counts: dict[str, int] = {}
    for block in module.blocks:
        for item in block.items:
            counts[item.name.upper()] = counts.get(item.name.upper(), 0) + 1

    chunks: list[str] = []
    mapping: dict[str, str] = {}
    for block_index, block in enumerate(module.blocks, 1):
        region_id = slug(block.name, fallback=f"block-{block_index}")
        chunks.append(f"""
    region {region_id} (
        name: {_text(block.name)}
        title: {_text(block.name.replace('_', ' ').title())}
        type: staticContent
        layout {{
            sequence: {block_index * 10}
            slot: body
        }}
        appearance {{
            template: @/standard
            templateOptions: #DEFAULT#
        }}
        comments {{
            comments: {_fence(f'Forms block {block.name}; source table/view: {block.query_data_source_name or "not declared"}. Data binding requires schema review.')}
        }}
    )
""")
        for item_index, item in enumerate(block.items, 1):
            bare = item.name.upper()
            suffix = bare if counts[bare] == 1 else f"{block.name}_{bare}".upper()
            apex_name = re.sub(r"[^A-Z0-9_$#]", "_", f"P{page}_{suffix}")[:255]
            mapping[f"{block.name}.{item.name}".upper()] = apex_name
            if "button" in item.item_type.lower():
                button_id = slug(f"{block.name}-{item.name}", fallback=f"button-{item_index}")
                chunks.append(f"""
    button {button_id} (
        buttonName: {re.sub(r'[^A-Z0-9_$#]', '_', item.name.upper())[:255]}
        label: {_text(item.prompt or item.name.replace('_', ' ').title())}
        layout {{
            sequence: {item_index * 10}
            region: @{region_id}
            slot: next
        }}
        appearance {{
            buttonTemplate: @/text
            templateOptions: #DEFAULT#
        }}
    )
""")
                continue

            required = "\n            valueRequired: true" if item.required else ""
            max_length = (
                f"\n            maxLength: {item.max_length}"
                if item.max_length and _item_type(item) in {"textField", "textArea"}
                else ""
            )
            validation = (
                f"\n        validation {{{required}{max_length}\n        }}"
                if required or max_length
                else ""
            )
            chunks.append(f"""
    pageItem {apex_name} (
        type: {_item_type(item)}
        label {{
            label: {_text(item.prompt or item.name.replace('_', ' ').title())}
            alignment: left
        }}
        layout {{
            sequence: {item_index * 10}
            region: @{region_id}
            slot: regionBody
            alignment: left
        }}
        appearance {{
            template: @/optional-floating
            templateOptions: #DEFAULT#
        }}{validation}
        comments {{
            comments: {_fence(f'Forms item {block.name}.{item.name}; database column: {item.column_name or "none"}; data type: {item.data_type or "unknown"}.')}
        }}
    )
""")
    return chunks, mapping


def _approved_processes(store: Store, page: int) -> tuple[list[str], list[dict]]:
    chunks: list[str] = []
    manifest: list[dict] = []
    sequence = 10
    for view in store.all_views():
        if view.state != APPROVED:
            continue
        task = view.task
        code = re.sub(r":P0_([A-Za-z0-9_$#]+)", rf":P{page}_\1", view.code)
        process_id = slug(f"forms-{task['id']}", fallback=f"forms-{sequence}")
        proposal = view.proposal or {}
        note = (
            f"FormsLang approved conversion. Source: {task['kind']} {task['title']}. "
            f"Suggested target: {proposal.get('apex_target') or task.get('apex_hint') or 'review required'}. "
            "Generated as a disabled-by-default page process candidate; verify its execution point and condition in Page Designer."
        )
        chunks.append(f"""
    process {process_id} (
        name: {_text('Forms: ' + task['title'])}
        type: executeCode
        source {{
            plsqlCode:
                {_fence(code, 'plsql')}
        }}
        execution {{
            sequence: {sequence}
            point: processing
        }}
        serverSideCondition {{
            type: never
        }}
        comments {{
            comments: {_fence(note)}
        }}
    )
""")
        manifest.append({
            "task_id": task["id"],
            "source": f"{task['kind']} {task['title']}",
            "component": f"page {page} process {process_id}",
            "enabled": False,
            "reason": "execution point and condition require human confirmation",
        })
        sequence += 10
    return chunks, manifest


def _page(module: FormModule, store: Store, config: ApexExportConfig) -> tuple[str, dict]:
    items, item_mapping = _page_items(module, config.page)
    processes, process_mapping = _approved_processes(store, config.page)
    title = module.title or module.name
    body = f"""page {config.page} (
    name: {_text(title)}
    alias: {slug(module.name).upper()}
    title: {_text(title)}
    appearance {{
        pageTemplate: @/standard
        templateOptions: #DEFAULT#
    }}
    navigation {{
        cursorFocus: doNotFocusCursor
    }}
    security {{
        pageAccessProtection: argumentsMustHaveChecksum
        formAutoComplete: false
    }}
{''.join(items)}{''.join(processes)}
)
"""
    return body, {"items": item_mapping, "approved_components": process_mapping}


def export_apexlang(
    store: Store,
    module: FormModule,
    out_dir: Path | str,
    raw_config: dict | None = None,
) -> ApexExportResult:
    """Write an expanded APEXlang project, import ZIP, and review artifacts."""
    if not _TEMPLATE.is_dir():
        raise RuntimeError(f"APEXlang 26.1 template is missing: {_TEMPLATE}")
    config = ApexExportConfig.from_dict(raw_config, module)
    out = Path(out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)
    project = out / config.alias
    zip_path = out / f"{config.alias}.apex.zip"
    review = out / f"{config.alias}-review"

    with tempfile.TemporaryDirectory(prefix="formslang-apex-", dir=out) as tmp:
        staged = Path(tmp) / config.alias
        shutil.copytree(_TEMPLATE, staged)
        _write_lf(staged / "application.apx", _application(config))
        _write_lf(staged / "deployments" / "default.json", _deployment(config))
        _write_lf(
            staged / ".apex" / "apexlang.json",
            json.dumps({"mmdVersion": MMD_VERSION}, indent=2) + "\n",
        )

        page_text, mapping = _page(module, store, config)
        pages = staged / "pages"
        for old in pages.glob("p00001-*.apx"):
            old.unlink()
        page_file = pages / f"p{config.page:05d}-{slug(module.name)}.apx"
        _write_lf(page_file, page_text)

        brand = Path(__file__).resolve().parents[1] / "assets" / "brand" / "formslang-app-icon.svg"
        if brand.exists():
            static = staged / "shared-components" / "static-files"
            shutil.copy2(brand, static / "formslang-app-icon.svg")
            catalog = staged / "shared-components" / "static-files.apx"
            _write_lf(
                catalog,
                catalog.read_text(encoding="utf-8")
                + '\nfile "formslang-app-icon.svg" (\n'
                + '    mimeType: image/svg+xml\n'
                + '    charSet: utf-8\n'
                + ')\n',
            )

        if project.exists():
            shutil.rmtree(project)
        shutil.move(str(staged), str(project))

    if review.exists():
        shutil.rmtree(review)
    sql_path, json_path = store.export(review)
    manifest_path = review / "apexlang-manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "format": "APEXlang 26.1",
                "mmd_version": MMD_VERSION,
                "config": asdict(config),
                "source": store.session(),
                "stats": store.stats(),
                **mapping,
                "import": {
                    "validate": f"apex validate -input {config.alias}.apex.zip",
                    "command": f"apex import -input {config.alias}.apex.zip",
                    "database_required": True,
                },
            },
            ensure_ascii=False,
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file in sorted(p for p in project.rglob("*") if p.is_file()):
            archive.write(file, file.relative_to(project).as_posix())

    return ApexExportResult(
        project, zip_path, sql_path, json_path, manifest_path, store.stats()[APPROVED]
    )
